// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EvaluationStatus.
const (
	Completed      EvaluationStatus = "completed"
	ProviderFailed EvaluationStatus = "provider_failed"
	Rejected       EvaluationStatus = "rejected"
)

// Valid indicates whether the value is a known member of the EvaluationStatus enum.
func (e EvaluationStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case ProviderFailed:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionPath.
const (
	DecisionRule ExecutionPath = "decision_rule"
	Default      ExecutionPath = "default"
	PreRule      ExecutionPath = "pre_rule"
)

// Valid indicates whether the value is a known member of the ExecutionPath enum.
func (e ExecutionPath) Valid() bool {
	switch e {
	case DecisionRule:
		return true
	case Default:
		return true
	case PreRule:
		return true
	default:
		return false
	}
}

// Defines values for PolicyKind.
const (
	Inline PolicyKind = "inline"
	Named  PolicyKind = "named"
)

// Valid indicates whether the value is a known member of the PolicyKind enum.
func (e PolicyKind) Valid() bool {
	switch e {
	case Inline:
		return true
	case Named:
		return true
	default:
		return false
	}
}

// Defines values for QuestionType.
const (
	Choice QuestionType = "choice"
	Noul   QuestionType = "noul"
	Score  QuestionType = "score"
)

// Valid indicates whether the value is a known member of the QuestionType enum.
func (e QuestionType) Valid() bool {
	switch e {
	case Choice:
		return true
	case Noul:
		return true
	case Score:
		return true
	default:
		return false
	}
}

// Answer One typed answer. Which fields are present depends on `type`: a noul carries only `noul`, a choice carries `choice`, `confidence`, and `probabilities`, and a score carries `score`, `confidence`, `probabilities`, and `legend`.
type Answer struct {
	Choice        *string             `json:"choice,omitempty"`
	Confidence    *float64            `json:"confidence,omitempty"`
	Legend        *map[string]string  `json:"legend,omitempty"`
	Noul          *float64            `json:"noul,omitempty"`
	Probabilities *map[string]float64 `json:"probabilities,omitempty"`
	Score         *float64            `json:"score,omitempty"`
	Type          QuestionType        `json:"type"`
}

// CreateEvaluationRequest defines model for CreateEvaluationRequest.
type CreateEvaluationRequest struct {
	// Facts Trusted structured values the deterministic rules read.
	Facts *map[string]interface{} `json:"facts,omitempty"`

	// InlinePolicy A complete policy document. Refused unless the deployment enables inline policies. It is never written to the policy directory.
	InlinePolicy *map[string]interface{} `json:"inlinePolicy,omitempty"`

	// Metadata Bounded caller metadata recorded with the evaluation.
	Metadata  *map[string]string `json:"metadata,omitempty"`
	PolicyRef *PolicyRef         `json:"policyRef,omitempty"`

	// State The content to judge, a string or a structured value.
	State interface{} `json:"state"`
}

// Error The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type Error struct {
	Code    string      `json:"code"`
	Details interface{} `json:"details,omitempty"`
	Message string      `json:"message"`
}

// Evaluation defines model for Evaluation.
type Evaluation struct {
	Answers   map[string]Answer `json:"answers"`
	CreatedAt time.Time         `json:"createdAt"`

	// ExecutionPath How far the evaluation got before an outcome was selected. `pre_rule` means a deterministic rule decided it and no provider call was made.
	ExecutionPath ExecutionPath `json:"executionPath"`

	// FailureCode The stable error class when status is not completed.
	FailureCode *string            `json:"failureCode,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// MatchedRuleId The rule that selected the outcome, null when the default applied.
	MatchedRuleId *string            `json:"matchedRuleId,omitempty"`
	Metadata      *map[string]string `json:"metadata,omitempty"`
	Outcome       string             `json:"outcome"`
	Policy        PolicyRef          `json:"policy"`

	// PolicyHash SHA-256 of the exact policy that decided this evaluation.
	PolicyHash         string     `json:"policyHash"`
	PolicyKind         PolicyKind `json:"policyKind"`
	ProviderAttempts   *int       `json:"providerAttempts,omitempty"`
	ProviderDurationMs *int       `json:"providerDurationMs,omitempty"`
	RequestId          *string    `json:"requestId,omitempty"`
	RequestedModel     *string    `json:"requestedModel,omitempty"`

	// ResolvedModel The versioned model that actually answered.
	ResolvedModel   *string          `json:"resolvedModel,omitempty"`
	Status          EvaluationStatus `json:"status"`
	TotalDurationMs *int             `json:"totalDurationMs,omitempty"`
	Usage           Usage            `json:"usage"`
}

// EvaluationList Offset pagination with a hasMore probe rather than a count, because the evaluation table grows without bound.
type EvaluationList struct {
	HasMore bool         `json:"hasMore"`
	Items   []Evaluation `json:"items"`
	Limit   int          `json:"limit"`
	Offset  int          `json:"offset"`
}

// EvaluationStatus defines model for EvaluationStatus.
type EvaluationStatus string

// ExecutionPath How far the evaluation got before an outcome was selected. `pre_rule` means a deterministic rule decided it and no provider call was made.
type ExecutionPath string

// Feedback defines model for Feedback.
type Feedback struct {
	CreatedAt       time.Time          `json:"createdAt"`
	EvaluationId    openapi_types.UUID `json:"evaluationId"`
	ExpectedOutcome string             `json:"expectedOutcome"`
	Id              openapi_types.UUID `json:"id"`
	Note            *string            `json:"note,omitempty"`
}

// Policy defines model for Policy.
type Policy struct {
	DecisionRuleIds *[]string          `json:"decisionRuleIds,omitempty"`
	DefaultOutcome  string             `json:"defaultOutcome"`
	Description     *string            `json:"description,omitempty"`
	Hash            string             `json:"hash"`
	Model           *string            `json:"model,omitempty"`
	Name            string             `json:"name"`
	OptionalFacts   *map[string]string `json:"optionalFacts,omitempty"`
	Outcomes        []string           `json:"outcomes"`
	PreRuleIds      *[]string          `json:"preRuleIds,omitempty"`
	Questions       []PolicyQuestion   `json:"questions"`
	RequiredFacts   *map[string]string `json:"requiredFacts,omitempty"`
	StrictInput     *bool              `json:"strictInput,omitempty"`
	Version         string             `json:"version"`
}

// PolicyKind defines model for PolicyKind.
type PolicyKind string

// PolicyList defines model for PolicyList.
type PolicyList struct {
	Items []Policy `json:"items"`
}

// PolicyQuestion defines model for PolicyQuestion.
type PolicyQuestion struct {
	ChoiceCriteria *map[string]string `json:"choiceCriteria,omitempty"`
	Id             string             `json:"id"`
	Instructions   string             `json:"instructions"`
	ScoreCriteria  *[]string          `json:"scoreCriteria,omitempty"`
	Type           QuestionType       `json:"type"`
}

// PolicyRef defines model for PolicyRef.
type PolicyRef struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// PolicyValidation defines model for PolicyValidation.
type PolicyValidation struct {
	// Error Why the document failed to compile.
	Error  *string `json:"error,omitempty"`
	Policy *Policy `json:"policy,omitempty"`
	Valid  bool    `json:"valid"`
}

// QuestionType defines model for QuestionType.
type QuestionType string

// SubmitFeedbackRequest defines model for SubmitFeedbackRequest.
type SubmitFeedbackRequest struct {
	ExpectedOutcome string  `json:"expectedOutcome"`
	Note            *string `json:"note,omitempty"`
}

// Usage defines model for Usage.
type Usage struct {
	InputTokens  int `json:"inputTokens"`
	OutputTokens int `json:"outputTokens"`
}

// ValidatePolicyRequest defines model for ValidatePolicyRequest.
type ValidatePolicyRequest struct {
	// Policy The policy document to compile.
	Policy map[string]interface{} `json:"policy"`
}

// EvaluationID defines model for EvaluationID.
type EvaluationID = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadGateway The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type BadGateway = Error

// BadRequest The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type BadRequest = Error

// Conflict The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type Conflict = Error

// GatewayTimeout The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type GatewayTimeout = Error

// InternalServerError The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type InternalServerError = Error

// NotFound The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type NotFound = Error

// PayloadTooLarge The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type PayloadTooLarge = Error

// ServiceUnavailable The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type ServiceUnavailable = Error

// TooManyRequests The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type TooManyRequests = Error

// Unauthorized The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type Unauthorized = Error

// UnprocessableEntity The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type UnprocessableEntity = Error

// ListEvaluationsParams defines parameters for ListEvaluations.
type ListEvaluationsParams struct {
	Limit         *Limit            `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *Offset           `form:"offset,omitempty" json:"offset,omitempty"`
	PolicyName    *string           `form:"policyName,omitempty" json:"policyName,omitempty"`
	PolicyVersion *string           `form:"policyVersion,omitempty" json:"policyVersion,omitempty"`
	Outcome       *string           `form:"outcome,omitempty" json:"outcome,omitempty"`
	Status        *EvaluationStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateEvaluationParams defines parameters for CreateEvaluation.
type CreateEvaluationParams struct {
	// IdempotencyKey A caller-chosen UUID that makes this request replayable.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateEvaluationJSONRequestBody defines body for CreateEvaluation for application/json ContentType.
type CreateEvaluationJSONRequestBody = CreateEvaluationRequest

// SubmitFeedbackJSONRequestBody defines body for SubmitFeedback for application/json ContentType.
type SubmitFeedbackJSONRequestBody = SubmitFeedbackRequest

// ValidatePolicyJSONRequestBody defines body for ValidatePolicy for application/json ContentType.
type ValidatePolicyJSONRequestBody = ValidatePolicyRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListEvaluations List recorded evaluations
	//
	// Newest first, with the evaluation ID as a stable tiebreaker.
	//
	// Corresponds with GET /evaluations (the `ListEvaluations` operationId).
	ListEvaluations(ctx context.Context, params *ListEvaluationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateEvaluationWithBody Evaluate state against a policy
	//
	// Synchronous. Exactly one of policyRef or inlinePolicy must be supplied. Inline policies are refused unless the deployment enables them.
	// Supplying an Idempotency-Key replays the original evaluation when the canonical request is identical, and conflicts when it is not.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /evaluations (the `CreateEvaluation` operationId).
	CreateEvaluationWithBody(ctx context.Context, params *CreateEvaluationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateEvaluation Evaluate state against a policy
	//
	// Synchronous. Exactly one of policyRef or inlinePolicy must be supplied. Inline policies are refused unless the deployment enables them.
	// Supplying an Idempotency-Key replays the original evaluation when the canonical request is identical, and conflicts when it is not.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /evaluations (the `CreateEvaluation` operationId).
	CreateEvaluation(ctx context.Context, params *CreateEvaluationParams, body CreateEvaluationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEvaluation Fetch one evaluation
	//
	// Corresponds with GET /evaluations/{evaluationId} (the `GetEvaluation` operationId).
	GetEvaluation(ctx context.Context, evaluationId EvaluationID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitFeedbackWithBody Record the outcome a human expected
	//
	// Feedback is calibration data. It never changes a recorded decision and never influences a future one.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /evaluations/{evaluationId}/feedback (the `SubmitFeedback` operationId).
	SubmitFeedbackWithBody(ctx context.Context, evaluationId EvaluationID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitFeedback Record the outcome a human expected
	//
	// Feedback is calibration data. It never changes a recorded decision and never influences a future one.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /evaluations/{evaluationId}/feedback (the `SubmitFeedback` operationId).
	SubmitFeedback(ctx context.Context, evaluationId EvaluationID, body SubmitFeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPolicies List loaded policies
	//
	// Corresponds with GET /policies (the `ListPolicies` operationId).
	ListPolicies(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ValidatePolicyWithBody Compile a policy document without installing it
	//
	// Compiles the supplied document and reports whether it is valid. Nothing is written to the policy directory and nothing is loaded.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /policies/validate (the `ValidatePolicy` operationId).
	ValidatePolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ValidatePolicy Compile a policy document without installing it
	//
	// Compiles the supplied document and reports whether it is valid. Nothing is written to the policy directory and nothing is loaded.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /policies/validate (the `ValidatePolicy` operationId).
	ValidatePolicy(ctx context.Context, body ValidatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPolicy Fetch one loaded policy
	//
	// Corresponds with GET /policies/{policyName}/versions/{policyVersion} (the `GetPolicy` operationId).
	GetPolicy(ctx context.Context, policyName string, policyVersion string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListEvaluations List recorded evaluations
//
// Newest first, with the evaluation ID as a stable tiebreaker.
//
// Corresponds with GET /evaluations (the `ListEvaluations` operationId).
func (c *Client) ListEvaluations(ctx context.Context, params *ListEvaluationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEvaluationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateEvaluationWithBody Evaluate state against a policy
//
// Synchronous. Exactly one of policyRef or inlinePolicy must be supplied. Inline policies are refused unless the deployment enables them.
// Supplying an Idempotency-Key replays the original evaluation when the canonical request is identical, and conflicts when it is not.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /evaluations (the `CreateEvaluation` operationId).
func (c *Client) CreateEvaluationWithBody(ctx context.Context, params *CreateEvaluationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEvaluationRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateEvaluation Evaluate state against a policy
//
// Synchronous. Exactly one of policyRef or inlinePolicy must be supplied. Inline policies are refused unless the deployment enables them.
// Supplying an Idempotency-Key replays the original evaluation when the canonical request is identical, and conflicts when it is not.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /evaluations (the `CreateEvaluation` operationId).
func (c *Client) CreateEvaluation(ctx context.Context, params *CreateEvaluationParams, body CreateEvaluationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEvaluationRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetEvaluation Fetch one evaluation
//
// Corresponds with GET /evaluations/{evaluationId} (the `GetEvaluation` operationId).
func (c *Client) GetEvaluation(ctx context.Context, evaluationId EvaluationID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEvaluationRequest(c.Server, evaluationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SubmitFeedbackWithBody Record the outcome a human expected
//
// Feedback is calibration data. It never changes a recorded decision and never influences a future one.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /evaluations/{evaluationId}/feedback (the `SubmitFeedback` operationId).
func (c *Client) SubmitFeedbackWithBody(ctx context.Context, evaluationId EvaluationID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitFeedbackRequestWithBody(c.Server, evaluationId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SubmitFeedback Record the outcome a human expected
//
// Feedback is calibration data. It never changes a recorded decision and never influences a future one.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /evaluations/{evaluationId}/feedback (the `SubmitFeedback` operationId).
func (c *Client) SubmitFeedback(ctx context.Context, evaluationId EvaluationID, body SubmitFeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitFeedbackRequest(c.Server, evaluationId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListPolicies List loaded policies
//
// Corresponds with GET /policies (the `ListPolicies` operationId).
func (c *Client) ListPolicies(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPoliciesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ValidatePolicyWithBody Compile a policy document without installing it
//
// Compiles the supplied document and reports whether it is valid. Nothing is written to the policy directory and nothing is loaded.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /policies/validate (the `ValidatePolicy` operationId).
func (c *Client) ValidatePolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidatePolicyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ValidatePolicy Compile a policy document without installing it
//
// Compiles the supplied document and reports whether it is valid. Nothing is written to the policy directory and nothing is loaded.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /policies/validate (the `ValidatePolicy` operationId).
func (c *Client) ValidatePolicy(ctx context.Context, body ValidatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidatePolicyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPolicy Fetch one loaded policy
//
// Corresponds with GET /policies/{policyName}/versions/{policyVersion} (the `GetPolicy` operationId).
func (c *Client) GetPolicy(ctx context.Context, policyName string, policyVersion string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPolicyRequest(c.Server, policyName, policyVersion)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListEvaluationsRequest constructs an http.Request for the ListEvaluations method
func NewListEvaluationsRequest(server string, params *ListEvaluationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/evaluations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PolicyName != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "policyName", *params.PolicyName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PolicyVersion != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "policyVersion", *params.PolicyVersion, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Outcome != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "outcome", *params.Outcome, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateEvaluationRequest calls the generic CreateEvaluation builder with application/json body
func NewCreateEvaluationRequest(server string, params *CreateEvaluationParams, body CreateEvaluationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateEvaluationRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateEvaluationRequestWithBody constructs an http.Request for the CreateEvaluation method, with any body, and a specified content type
func NewCreateEvaluationRequestWithBody(server string, params *CreateEvaluationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/evaluations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.IdempotencyKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", *params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: "uuid"})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetEvaluationRequest constructs an http.Request for the GetEvaluation method
func NewGetEvaluationRequest(server string, evaluationId EvaluationID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "evaluationId", evaluationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/evaluations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSubmitFeedbackRequest calls the generic SubmitFeedback builder with application/json body
func NewSubmitFeedbackRequest(server string, evaluationId EvaluationID, body SubmitFeedbackJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubmitFeedbackRequestWithBody(server, evaluationId, "application/json", bodyReader)
}

// NewSubmitFeedbackRequestWithBody constructs an http.Request for the SubmitFeedback method, with any body, and a specified content type
func NewSubmitFeedbackRequestWithBody(server string, evaluationId EvaluationID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "evaluationId", evaluationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/evaluations/%s/feedback", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListPoliciesRequest constructs an http.Request for the ListPolicies method
func NewListPoliciesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policies")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewValidatePolicyRequest calls the generic ValidatePolicy builder with application/json body
func NewValidatePolicyRequest(server string, body ValidatePolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewValidatePolicyRequestWithBody(server, "application/json", bodyReader)
}

// NewValidatePolicyRequestWithBody constructs an http.Request for the ValidatePolicy method, with any body, and a specified content type
func NewValidatePolicyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policies/validate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPolicyRequest constructs an http.Request for the GetPolicy method
func NewGetPolicyRequest(server string, policyName string, policyVersion string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "policyName", policyName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "policyVersion", policyVersion, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policies/%s/versions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListEvaluationsWithResponse List recorded evaluations
	//
	// Newest first, with the evaluation ID as a stable tiebreaker.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /evaluations (the `ListEvaluations` operationId).
	ListEvaluationsWithResponse(ctx context.Context, params *ListEvaluationsParams, reqEditors ...RequestEditorFn) (*ListEvaluationsResponse, error)

	// CreateEvaluationWithBodyWithResponse Evaluate state against a policy
	//
	// Synchronous. Exactly one of policyRef or inlinePolicy must be supplied. Inline policies are refused unless the deployment enables them.
	// Supplying an Idempotency-Key replays the original evaluation when the canonical request is identical, and conflicts when it is not.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /evaluations (the `CreateEvaluation` operationId).
	CreateEvaluationWithBodyWithResponse(ctx context.Context, params *CreateEvaluationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEvaluationResponse, error)

	// CreateEvaluationWithResponse Evaluate state against a policy
	//
	// Synchronous. Exactly one of policyRef or inlinePolicy must be supplied. Inline policies are refused unless the deployment enables them.
	// Supplying an Idempotency-Key replays the original evaluation when the canonical request is identical, and conflicts when it is not.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /evaluations (the `CreateEvaluation` operationId).
	CreateEvaluationWithResponse(ctx context.Context, params *CreateEvaluationParams, body CreateEvaluationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEvaluationResponse, error)

	// GetEvaluationWithResponse Fetch one evaluation
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /evaluations/{evaluationId} (the `GetEvaluation` operationId).
	GetEvaluationWithResponse(ctx context.Context, evaluationId EvaluationID, reqEditors ...RequestEditorFn) (*GetEvaluationResponse, error)

	// SubmitFeedbackWithBodyWithResponse Record the outcome a human expected
	//
	// Feedback is calibration data. It never changes a recorded decision and never influences a future one.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /evaluations/{evaluationId}/feedback (the `SubmitFeedback` operationId).
	SubmitFeedbackWithBodyWithResponse(ctx context.Context, evaluationId EvaluationID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitFeedbackResponse, error)

	// SubmitFeedbackWithResponse Record the outcome a human expected
	//
	// Feedback is calibration data. It never changes a recorded decision and never influences a future one.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /evaluations/{evaluationId}/feedback (the `SubmitFeedback` operationId).
	SubmitFeedbackWithResponse(ctx context.Context, evaluationId EvaluationID, body SubmitFeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitFeedbackResponse, error)

	// ListPoliciesWithResponse List loaded policies
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /policies (the `ListPolicies` operationId).
	ListPoliciesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPoliciesResponse, error)

	// ValidatePolicyWithBodyWithResponse Compile a policy document without installing it
	//
	// Compiles the supplied document and reports whether it is valid. Nothing is written to the policy directory and nothing is loaded.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /policies/validate (the `ValidatePolicy` operationId).
	ValidatePolicyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ValidatePolicyResponse, error)

	// ValidatePolicyWithResponse Compile a policy document without installing it
	//
	// Compiles the supplied document and reports whether it is valid. Nothing is written to the policy directory and nothing is loaded.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /policies/validate (the `ValidatePolicy` operationId).
	ValidatePolicyWithResponse(ctx context.Context, body ValidatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*ValidatePolicyResponse, error)

	// GetPolicyWithResponse Fetch one loaded policy
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /policies/{policyName}/versions/{policyVersion} (the `GetPolicy` operationId).
	GetPolicyWithResponse(ctx context.Context, policyName string, policyVersion string, reqEditors ...RequestEditorFn) (*GetPolicyResponse, error)
}

type ListEvaluationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *EvaluationList
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListEvaluationsResponse) GetJSON200() *EvaluationList {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListEvaluationsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListEvaluationsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListEvaluationsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListEvaluationsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListEvaluationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEvaluationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListEvaluationsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateEvaluationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Evaluation
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *PayloadTooLarge
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *UnprocessableEntity
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *TooManyRequests
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
	// JSON502 the response for an HTTP 502 `application/json` response
	JSON502 *BadGateway
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *ServiceUnavailable
	// JSON504 the response for an HTTP 504 `application/json` response
	JSON504 *GatewayTimeout
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateEvaluationResponse) GetJSON201() *Evaluation {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateEvaluationResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreateEvaluationResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CreateEvaluationResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateEvaluationResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r CreateEvaluationResponse) GetJSON413() *PayloadTooLarge {
	return r.JSON413
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CreateEvaluationResponse) GetJSON422() *UnprocessableEntity {
	return r.JSON422
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r CreateEvaluationResponse) GetJSON429() *TooManyRequests {
	return r.JSON429
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreateEvaluationResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetJSON502 returns the response for an HTTP 502 `application/json` response
func (r CreateEvaluationResponse) GetJSON502() *BadGateway {
	return r.JSON502
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r CreateEvaluationResponse) GetJSON503() *ServiceUnavailable {
	return r.JSON503
}

// GetJSON504 returns the response for an HTTP 504 `application/json` response
func (r CreateEvaluationResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

// GetBody returns the raw response body bytes
func (r CreateEvaluationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateEvaluationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateEvaluationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateEvaluationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetEvaluationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Evaluation
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetEvaluationResponse) GetJSON200() *Evaluation {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetEvaluationResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetEvaluationResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetEvaluationResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetEvaluationResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetEvaluationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetEvaluationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEvaluationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetEvaluationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SubmitFeedbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Feedback
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *UnprocessableEntity
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r SubmitFeedbackResponse) GetJSON201() *Feedback {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SubmitFeedbackResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r SubmitFeedbackResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r SubmitFeedbackResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r SubmitFeedbackResponse) GetJSON422() *UnprocessableEntity {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r SubmitFeedbackResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r SubmitFeedbackResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SubmitFeedbackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubmitFeedbackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SubmitFeedbackResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListPoliciesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *PolicyList
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListPoliciesResponse) GetJSON200() *PolicyList {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListPoliciesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListPoliciesResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListPoliciesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListPoliciesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPoliciesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPoliciesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ValidatePolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *PolicyValidation
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *PayloadTooLarge
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ValidatePolicyResponse) GetJSON200() *PolicyValidation {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ValidatePolicyResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ValidatePolicyResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r ValidatePolicyResponse) GetJSON413() *PayloadTooLarge {
	return r.JSON413
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ValidatePolicyResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ValidatePolicyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ValidatePolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ValidatePolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ValidatePolicyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Policy
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPolicyResponse) GetJSON200() *Policy {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetPolicyResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetPolicyResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetPolicyResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetPolicyResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetPolicyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPolicyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListEvaluationsWithResponse List recorded evaluations
//
// Newest first, with the evaluation ID as a stable tiebreaker.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /evaluations (the `ListEvaluations` operationId).
func (c *ClientWithResponses) ListEvaluationsWithResponse(ctx context.Context, params *ListEvaluationsParams, reqEditors ...RequestEditorFn) (*ListEvaluationsResponse, error) {
	rsp, err := c.ListEvaluations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEvaluationsResponse(rsp)
}

// CreateEvaluationWithBodyWithResponse Evaluate state against a policy
//
// Synchronous. Exactly one of policyRef or inlinePolicy must be supplied. Inline policies are refused unless the deployment enables them.
// Supplying an Idempotency-Key replays the original evaluation when the canonical request is identical, and conflicts when it is not.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /evaluations (the `CreateEvaluation` operationId).
func (c *ClientWithResponses) CreateEvaluationWithBodyWithResponse(ctx context.Context, params *CreateEvaluationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEvaluationResponse, error) {
	rsp, err := c.CreateEvaluationWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEvaluationResponse(rsp)
}

// CreateEvaluationWithResponse Evaluate state against a policy
//
// Synchronous. Exactly one of policyRef or inlinePolicy must be supplied. Inline policies are refused unless the deployment enables them.
// Supplying an Idempotency-Key replays the original evaluation when the canonical request is identical, and conflicts when it is not.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /evaluations (the `CreateEvaluation` operationId).
func (c *ClientWithResponses) CreateEvaluationWithResponse(ctx context.Context, params *CreateEvaluationParams, body CreateEvaluationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEvaluationResponse, error) {
	rsp, err := c.CreateEvaluation(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEvaluationResponse(rsp)
}

// GetEvaluationWithResponse Fetch one evaluation
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /evaluations/{evaluationId} (the `GetEvaluation` operationId).
func (c *ClientWithResponses) GetEvaluationWithResponse(ctx context.Context, evaluationId EvaluationID, reqEditors ...RequestEditorFn) (*GetEvaluationResponse, error) {
	rsp, err := c.GetEvaluation(ctx, evaluationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEvaluationResponse(rsp)
}

// SubmitFeedbackWithBodyWithResponse Record the outcome a human expected
//
// Feedback is calibration data. It never changes a recorded decision and never influences a future one.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /evaluations/{evaluationId}/feedback (the `SubmitFeedback` operationId).
func (c *ClientWithResponses) SubmitFeedbackWithBodyWithResponse(ctx context.Context, evaluationId EvaluationID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitFeedbackResponse, error) {
	rsp, err := c.SubmitFeedbackWithBody(ctx, evaluationId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitFeedbackResponse(rsp)
}

// SubmitFeedbackWithResponse Record the outcome a human expected
//
// Feedback is calibration data. It never changes a recorded decision and never influences a future one.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /evaluations/{evaluationId}/feedback (the `SubmitFeedback` operationId).
func (c *ClientWithResponses) SubmitFeedbackWithResponse(ctx context.Context, evaluationId EvaluationID, body SubmitFeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitFeedbackResponse, error) {
	rsp, err := c.SubmitFeedback(ctx, evaluationId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitFeedbackResponse(rsp)
}

// ListPoliciesWithResponse List loaded policies
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /policies (the `ListPolicies` operationId).
func (c *ClientWithResponses) ListPoliciesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPoliciesResponse, error) {
	rsp, err := c.ListPolicies(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPoliciesResponse(rsp)
}

// ValidatePolicyWithBodyWithResponse Compile a policy document without installing it
//
// Compiles the supplied document and reports whether it is valid. Nothing is written to the policy directory and nothing is loaded.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /policies/validate (the `ValidatePolicy` operationId).
func (c *ClientWithResponses) ValidatePolicyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ValidatePolicyResponse, error) {
	rsp, err := c.ValidatePolicyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidatePolicyResponse(rsp)
}

// ValidatePolicyWithResponse Compile a policy document without installing it
//
// Compiles the supplied document and reports whether it is valid. Nothing is written to the policy directory and nothing is loaded.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /policies/validate (the `ValidatePolicy` operationId).
func (c *ClientWithResponses) ValidatePolicyWithResponse(ctx context.Context, body ValidatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*ValidatePolicyResponse, error) {
	rsp, err := c.ValidatePolicy(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidatePolicyResponse(rsp)
}

// GetPolicyWithResponse Fetch one loaded policy
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /policies/{policyName}/versions/{policyVersion} (the `GetPolicy` operationId).
func (c *ClientWithResponses) GetPolicyWithResponse(ctx context.Context, policyName string, policyVersion string, reqEditors ...RequestEditorFn) (*GetPolicyResponse, error) {
	rsp, err := c.GetPolicy(ctx, policyName, policyVersion, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPolicyResponse(rsp)
}

// ParseListEvaluationsResponse parses an HTTP response from a ListEvaluationsWithResponse call
func ParseListEvaluationsResponse(rsp *http.Response) (*ListEvaluationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEvaluationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EvaluationList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateEvaluationResponse parses an HTTP response from a CreateEvaluationWithResponse call
func ParseCreateEvaluationResponse(rsp *http.Response) (*CreateEvaluationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateEvaluationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Evaluation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest PayloadTooLarge
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGateway
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ServiceUnavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest GatewayTimeout
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON504 = &dest

	}

	return response, nil
}

// ParseGetEvaluationResponse parses an HTTP response from a GetEvaluationWithResponse call
func ParseGetEvaluationResponse(rsp *http.Response) (*GetEvaluationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEvaluationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Evaluation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseSubmitFeedbackResponse parses an HTTP response from a SubmitFeedbackWithResponse call
func ParseSubmitFeedbackResponse(rsp *http.Response) (*SubmitFeedbackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubmitFeedbackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Feedback
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListPoliciesResponse parses an HTTP response from a ListPoliciesWithResponse call
func ParseListPoliciesResponse(rsp *http.Response) (*ListPoliciesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPoliciesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseValidatePolicyResponse parses an HTTP response from a ValidatePolicyWithResponse call
func ParseValidatePolicyResponse(rsp *http.Response) (*ValidatePolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ValidatePolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyValidation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest PayloadTooLarge
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPolicyResponse parses an HTTP response from a GetPolicyWithResponse call
func ParseGetPolicyResponse(rsp *http.Response) (*GetPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Policy
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
