//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EvaluationStatus.
const (
	Completed      EvaluationStatus = "completed"
	ProviderFailed EvaluationStatus = "provider_failed"
	Rejected       EvaluationStatus = "rejected"
)

// Valid indicates whether the value is a known member of the EvaluationStatus enum.
func (e EvaluationStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case ProviderFailed:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionPath.
const (
	DecisionRule ExecutionPath = "decision_rule"
	Default      ExecutionPath = "default"
	PreRule      ExecutionPath = "pre_rule"
)

// Valid indicates whether the value is a known member of the ExecutionPath enum.
func (e ExecutionPath) Valid() bool {
	switch e {
	case DecisionRule:
		return true
	case Default:
		return true
	case PreRule:
		return true
	default:
		return false
	}
}

// Defines values for PolicyKind.
const (
	Inline PolicyKind = "inline"
	Named  PolicyKind = "named"
)

// Valid indicates whether the value is a known member of the PolicyKind enum.
func (e PolicyKind) Valid() bool {
	switch e {
	case Inline:
		return true
	case Named:
		return true
	default:
		return false
	}
}

// Defines values for QuestionType.
const (
	Choice QuestionType = "choice"
	Noul   QuestionType = "noul"
	Score  QuestionType = "score"
)

// Valid indicates whether the value is a known member of the QuestionType enum.
func (e QuestionType) Valid() bool {
	switch e {
	case Choice:
		return true
	case Noul:
		return true
	case Score:
		return true
	default:
		return false
	}
}

// Answer One typed answer. Which fields are present depends on `type`: a noul carries only `noul`, a choice carries `choice`, `confidence`, and `probabilities`, and a score carries `score`, `confidence`, `probabilities`, and `legend`.
type Answer struct {
	Choice     *string  `json:"choice,omitempty"`
	Confidence *float64 `json:"confidence,omitempty"`

	// Legend The declared score criteria keyed by numeric level.
	Legend        *map[string]interface{} `json:"legend,omitempty"`
	Noul          *float64                `json:"noul,omitempty"`
	Probabilities *map[string]float64     `json:"probabilities,omitempty"`
	Score         *float64                `json:"score,omitempty"`
	Type          QuestionType            `json:"type"`
}

// CreateEvaluationRequest defines model for CreateEvaluationRequest.
type CreateEvaluationRequest struct {
	// Facts Trusted structured values the deterministic rules read.
	Facts *map[string]interface{} `json:"facts,omitempty"`

	// InlinePolicy A complete policy document. Refused unless the deployment enables inline policies. It is never written to the policy directory.
	InlinePolicy *map[string]interface{} `json:"inlinePolicy,omitempty"`

	// Metadata Bounded caller metadata recorded with the evaluation.
	Metadata  *map[string]string `json:"metadata,omitempty"`
	PolicyRef *PolicyRef         `json:"policyRef,omitempty"`

	// State The content to judge, a string or a structured value.
	State interface{} `json:"state"`
}

// Error The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type Error struct {
	Code    string      `json:"code"`
	Details interface{} `json:"details,omitempty"`
	Message string      `json:"message"`
}

// Evaluation defines model for Evaluation.
type Evaluation struct {
	Answers   map[string]Answer `json:"answers"`
	CreatedAt time.Time         `json:"createdAt"`

	// ExecutionPath How far the evaluation got before an outcome was selected. `pre_rule` means a deterministic rule decided it and no provider call was made.
	ExecutionPath ExecutionPath `json:"executionPath"`

	// FailureCode The stable error class when status is not completed.
	FailureCode *string            `json:"failureCode,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// MatchedRuleId The rule that selected the outcome, null when the default applied.
	MatchedRuleId *string            `json:"matchedRuleId,omitempty"`
	Metadata      *map[string]string `json:"metadata,omitempty"`
	Outcome       string             `json:"outcome"`
	Policy        PolicyRef          `json:"policy"`

	// PolicyHash SHA-256 of the exact policy that decided this evaluation.
	PolicyHash         string     `json:"policyHash"`
	PolicyKind         PolicyKind `json:"policyKind"`
	ProviderAttempts   *int       `json:"providerAttempts,omitempty"`
	ProviderDurationMs *int       `json:"providerDurationMs,omitempty"`
	RequestId          *string    `json:"requestId,omitempty"`
	RequestedModel     *string    `json:"requestedModel,omitempty"`

	// ResolvedModel The versioned model that actually answered.
	ResolvedModel   *string          `json:"resolvedModel,omitempty"`
	Status          EvaluationStatus `json:"status"`
	TotalDurationMs *int             `json:"totalDurationMs,omitempty"`
	Usage           Usage            `json:"usage"`
}

// EvaluationList Offset pagination with a hasMore probe rather than a count, because the evaluation table grows without bound.
type EvaluationList struct {
	HasMore bool         `json:"hasMore"`
	Items   []Evaluation `json:"items"`
	Limit   int          `json:"limit"`
	Offset  int          `json:"offset"`
}

// EvaluationStatus defines model for EvaluationStatus.
type EvaluationStatus string

// ExecutionPath How far the evaluation got before an outcome was selected. `pre_rule` means a deterministic rule decided it and no provider call was made.
type ExecutionPath string

// Feedback defines model for Feedback.
type Feedback struct {
	CreatedAt       time.Time          `json:"createdAt"`
	EvaluationId    openapi_types.UUID `json:"evaluationId"`
	ExpectedOutcome string             `json:"expectedOutcome"`
	Id              openapi_types.UUID `json:"id"`
	Note            *string            `json:"note,omitempty"`
}

// Policy defines model for Policy.
type Policy struct {
	DecisionRuleIds *[]string          `json:"decisionRuleIds,omitempty"`
	DefaultOutcome  string             `json:"defaultOutcome"`
	Description     *string            `json:"description,omitempty"`
	Hash            string             `json:"hash"`
	Model           *string            `json:"model,omitempty"`
	Name            string             `json:"name"`
	OptionalFacts   *map[string]string `json:"optionalFacts,omitempty"`
	Outcomes        []string           `json:"outcomes"`
	PreRuleIds      *[]string          `json:"preRuleIds,omitempty"`
	Questions       []PolicyQuestion   `json:"questions"`
	RequiredFacts   *map[string]string `json:"requiredFacts,omitempty"`
	StrictInput     *bool              `json:"strictInput,omitempty"`
	Version         string             `json:"version"`
}

// PolicyKind defines model for PolicyKind.
type PolicyKind string

// PolicyList defines model for PolicyList.
type PolicyList struct {
	Items []Policy `json:"items"`
}

// PolicyQuestion defines model for PolicyQuestion.
type PolicyQuestion struct {
	ChoiceCriteria *map[string]interface{} `json:"choiceCriteria,omitempty"`
	Id             string                  `json:"id"`

	// Instructions Optional string or structured TypeSafe instructions.
	Instructions  interface{}             `json:"instructions"`
	NoulCriteria  *map[string]interface{} `json:"noulCriteria,omitempty"`
	ScoreCriteria *[]interface{}          `json:"scoreCriteria,omitempty"`
	Type          QuestionType            `json:"type"`
}

// PolicyRef defines model for PolicyRef.
type PolicyRef struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// PolicyValidation defines model for PolicyValidation.
type PolicyValidation struct {
	// Error Why the document failed to compile.
	Error  *string `json:"error,omitempty"`
	Policy *Policy `json:"policy,omitempty"`
	Valid  bool    `json:"valid"`
}

// QuestionType defines model for QuestionType.
type QuestionType string

// SubmitFeedbackRequest defines model for SubmitFeedbackRequest.
type SubmitFeedbackRequest struct {
	ExpectedOutcome string  `json:"expectedOutcome"`
	Note            *string `json:"note,omitempty"`
}

// Usage defines model for Usage.
type Usage struct {
	InputTokens  int `json:"inputTokens"`
	OutputTokens int `json:"outputTokens"`
}

// ValidatePolicyRequest defines model for ValidatePolicyRequest.
type ValidatePolicyRequest struct {
	// Policy The policy document to compile.
	Policy map[string]interface{} `json:"policy"`
}

// EvaluationID defines model for EvaluationID.
type EvaluationID = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadGateway The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type BadGateway = Error

// BadRequest The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type BadRequest = Error

// Conflict The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type Conflict = Error

// GatewayTimeout The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type GatewayTimeout = Error

// InternalServerError The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type InternalServerError = Error

// NotFound The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type NotFound = Error

// PayloadTooLarge The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type PayloadTooLarge = Error

// ServiceUnavailable The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type ServiceUnavailable = Error

// TooManyRequests The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type TooManyRequests = Error

// Unauthorized The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type Unauthorized = Error

// UnprocessableEntity The error envelope every failure uses. `code` is stable UPPER_SNAKE_CASE and is the value a client switches on.
type UnprocessableEntity = Error

// ListEvaluationsParams defines parameters for ListEvaluations.
type ListEvaluationsParams struct {
	Limit         *Limit            `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *Offset           `form:"offset,omitempty" json:"offset,omitempty"`
	PolicyName    *string           `form:"policyName,omitempty" json:"policyName,omitempty"`
	PolicyVersion *string           `form:"policyVersion,omitempty" json:"policyVersion,omitempty"`
	Outcome       *string           `form:"outcome,omitempty" json:"outcome,omitempty"`
	Status        *EvaluationStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateEvaluationParams defines parameters for CreateEvaluation.
type CreateEvaluationParams struct {
	// IdempotencyKey A caller-chosen UUID that makes this request replayable.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateEvaluationJSONRequestBody defines body for CreateEvaluation for application/json ContentType.
type CreateEvaluationJSONRequestBody = CreateEvaluationRequest

// SubmitFeedbackJSONRequestBody defines body for SubmitFeedback for application/json ContentType.
type SubmitFeedbackJSONRequestBody = SubmitFeedbackRequest

// ValidatePolicyJSONRequestBody defines body for ValidatePolicy for application/json ContentType.
type ValidatePolicyJSONRequestBody = ValidatePolicyRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListEvaluations List recorded evaluations
	// (GET /evaluations)
	ListEvaluations(w http.ResponseWriter, r *http.Request, params ListEvaluationsParams)
	// CreateEvaluation Evaluate state against a policy
	// (POST /evaluations)
	CreateEvaluation(w http.ResponseWriter, r *http.Request, params CreateEvaluationParams)
	// GetEvaluation Fetch one evaluation
	// (GET /evaluations/{evaluationId})
	GetEvaluation(w http.ResponseWriter, r *http.Request, evaluationId EvaluationID)
	// SubmitFeedback Record the outcome a human expected
	// (POST /evaluations/{evaluationId}/feedback)
	SubmitFeedback(w http.ResponseWriter, r *http.Request, evaluationId EvaluationID)
	// ListPolicies List loaded policies
	// (GET /policies)
	ListPolicies(w http.ResponseWriter, r *http.Request)
	// ValidatePolicy Compile a policy document without installing it
	// (POST /policies/validate)
	ValidatePolicy(w http.ResponseWriter, r *http.Request)
	// GetPolicy Fetch one loaded policy
	// (GET /policies/{policyName}/versions/{policyVersion})
	GetPolicy(w http.ResponseWriter, r *http.Request, policyName string, policyVersion string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEvaluations operation middleware
func (siw *ServerInterfaceWrapper) ListEvaluations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEvaluationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "policyName" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "policyName", r.URL.Query(), &params.PolicyName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "policyName"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyName", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "policyVersion" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "policyVersion", r.URL.Query(), &params.PolicyVersion, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "policyVersion"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyVersion", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "outcome" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "outcome", r.URL.Query(), &params.Outcome, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "outcome"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "outcome", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvaluations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvaluation operation middleware
func (siw *ServerInterfaceWrapper) CreateEvaluation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateEvaluationParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvaluation(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvaluation operation middleware
func (siw *ServerInterfaceWrapper) GetEvaluation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "evaluationId" -------------
	var evaluationId EvaluationID

	err = runtime.BindStyledParameterWithOptions("simple", "evaluationId", r.PathValue("evaluationId"), &evaluationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "evaluationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvaluation(w, r, evaluationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitFeedback operation middleware
func (siw *ServerInterfaceWrapper) SubmitFeedback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "evaluationId" -------------
	var evaluationId EvaluationID

	err = runtime.BindStyledParameterWithOptions("simple", "evaluationId", r.PathValue("evaluationId"), &evaluationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "evaluationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitFeedback(w, r, evaluationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPolicies operation middleware
func (siw *ServerInterfaceWrapper) ListPolicies(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPolicies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidatePolicy operation middleware
func (siw *ServerInterfaceWrapper) ValidatePolicy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidatePolicy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPolicy operation middleware
func (siw *ServerInterfaceWrapper) GetPolicy(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "policyName" -------------
	var policyName string

	err = runtime.BindStyledParameterWithOptions("simple", "policyName", r.PathValue("policyName"), &policyName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyName", Err: err})
		return
	}

	// ------------- Path parameter "policyVersion" -------------
	var policyVersion string

	err = runtime.BindStyledParameterWithOptions("simple", "policyVersion", r.PathValue("policyVersion"), &policyVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyVersion", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPolicy(w, r, policyName, policyVersion)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/evaluations", wrapper.ListEvaluations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/evaluations", wrapper.CreateEvaluation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/evaluations/{evaluationId}", wrapper.GetEvaluation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/evaluations/{evaluationId}/feedback", wrapper.SubmitFeedback)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/policies", wrapper.ListPolicies)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/policies/{policyName}/versions/{policyVersion}", wrapper.GetPolicy)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/policies/validate", wrapper.ValidatePolicy)

	return m
}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type GatewayTimeoutJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type PayloadTooLargeJSONResponse Error

type ServiceUnavailableJSONResponse Error

type TooManyRequestsJSONResponse Error

type UnauthorizedJSONResponse Error

type UnprocessableEntityJSONResponse Error

type ListEvaluationsRequestObject struct {
	Params ListEvaluationsParams
}

type ListEvaluationsResponseObject interface {
	VisitListEvaluationsResponse(w http.ResponseWriter) error
}

type ListEvaluations200JSONResponse EvaluationList

func (response ListEvaluations200JSONResponse) VisitListEvaluationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEvaluations400JSONResponse struct{ BadRequestJSONResponse }

func (response ListEvaluations400JSONResponse) VisitListEvaluationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListEvaluations401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListEvaluations401JSONResponse) VisitListEvaluationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListEvaluations500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListEvaluations500JSONResponse) VisitListEvaluationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluationRequestObject struct {
	Params CreateEvaluationParams
	Body   *CreateEvaluationJSONRequestBody
}

type CreateEvaluationResponseObject interface {
	VisitCreateEvaluationResponse(w http.ResponseWriter) error
}

type CreateEvaluation201JSONResponse Evaluation

func (response CreateEvaluation201JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateEvaluation400JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateEvaluation401JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateEvaluation404JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation409JSONResponse struct{ ConflictJSONResponse }

func (response CreateEvaluation409JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response CreateEvaluation413JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateEvaluation422JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateEvaluation429JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateEvaluation500JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation502JSONResponse struct{ BadGatewayJSONResponse }

func (response CreateEvaluation502JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CreateEvaluation503JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEvaluation504JSONResponse struct{ GatewayTimeoutJSONResponse }

func (response CreateEvaluation504JSONResponse) VisitCreateEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(504)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvaluationRequestObject struct {
	EvaluationId EvaluationID `json:"evaluationId"`
}

type GetEvaluationResponseObject interface {
	VisitGetEvaluationResponse(w http.ResponseWriter) error
}

type GetEvaluation200JSONResponse Evaluation

func (response GetEvaluation200JSONResponse) VisitGetEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvaluation400JSONResponse struct{ BadRequestJSONResponse }

func (response GetEvaluation400JSONResponse) VisitGetEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvaluation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEvaluation401JSONResponse) VisitGetEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvaluation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEvaluation404JSONResponse) VisitGetEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvaluation500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetEvaluation500JSONResponse) VisitGetEvaluationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitFeedbackRequestObject struct {
	EvaluationId EvaluationID `json:"evaluationId"`
	Body         *SubmitFeedbackJSONRequestBody
}

type SubmitFeedbackResponseObject interface {
	VisitSubmitFeedbackResponse(w http.ResponseWriter) error
}

type SubmitFeedback201JSONResponse Feedback

func (response SubmitFeedback201JSONResponse) VisitSubmitFeedbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitFeedback400JSONResponse struct{ BadRequestJSONResponse }

func (response SubmitFeedback400JSONResponse) VisitSubmitFeedbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitFeedback401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SubmitFeedback401JSONResponse) VisitSubmitFeedbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitFeedback404JSONResponse struct{ NotFoundJSONResponse }

func (response SubmitFeedback404JSONResponse) VisitSubmitFeedbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitFeedback422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response SubmitFeedback422JSONResponse) VisitSubmitFeedbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitFeedback500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response SubmitFeedback500JSONResponse) VisitSubmitFeedbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListPoliciesRequestObject struct {
}

type ListPoliciesResponseObject interface {
	VisitListPoliciesResponse(w http.ResponseWriter) error
}

type ListPolicies200JSONResponse PolicyList

func (response ListPolicies200JSONResponse) VisitListPoliciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPolicies401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPolicies401JSONResponse) VisitListPoliciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListPolicies500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListPolicies500JSONResponse) VisitListPoliciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ValidatePolicyRequestObject struct {
	Body *ValidatePolicyJSONRequestBody
}

type ValidatePolicyResponseObject interface {
	VisitValidatePolicyResponse(w http.ResponseWriter) error
}

type ValidatePolicy200JSONResponse PolicyValidation

func (response ValidatePolicy200JSONResponse) VisitValidatePolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ValidatePolicy400JSONResponse struct{ BadRequestJSONResponse }

func (response ValidatePolicy400JSONResponse) VisitValidatePolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ValidatePolicy401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ValidatePolicy401JSONResponse) VisitValidatePolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ValidatePolicy413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ValidatePolicy413JSONResponse) VisitValidatePolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ValidatePolicy500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ValidatePolicy500JSONResponse) VisitValidatePolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPolicyRequestObject struct {
	PolicyName    string `json:"policyName"`
	PolicyVersion string `json:"policyVersion"`
}

type GetPolicyResponseObject interface {
	VisitGetPolicyResponse(w http.ResponseWriter) error
}

type GetPolicy200JSONResponse Policy

func (response GetPolicy200JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPolicy400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPolicy400JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPolicy401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPolicy401JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPolicy404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPolicy404JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPolicy500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetPolicy500JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListEvaluations List recorded evaluations
	// (GET /evaluations)
	ListEvaluations(ctx context.Context, request ListEvaluationsRequestObject) (ListEvaluationsResponseObject, error)
	// CreateEvaluation Evaluate state against a policy
	// (POST /evaluations)
	CreateEvaluation(ctx context.Context, request CreateEvaluationRequestObject) (CreateEvaluationResponseObject, error)
	// GetEvaluation Fetch one evaluation
	// (GET /evaluations/{evaluationId})
	GetEvaluation(ctx context.Context, request GetEvaluationRequestObject) (GetEvaluationResponseObject, error)
	// SubmitFeedback Record the outcome a human expected
	// (POST /evaluations/{evaluationId}/feedback)
	SubmitFeedback(ctx context.Context, request SubmitFeedbackRequestObject) (SubmitFeedbackResponseObject, error)
	// ListPolicies List loaded policies
	// (GET /policies)
	ListPolicies(ctx context.Context, request ListPoliciesRequestObject) (ListPoliciesResponseObject, error)
	// ValidatePolicy Compile a policy document without installing it
	// (POST /policies/validate)
	ValidatePolicy(ctx context.Context, request ValidatePolicyRequestObject) (ValidatePolicyResponseObject, error)
	// GetPolicy Fetch one loaded policy
	// (GET /policies/{policyName}/versions/{policyVersion})
	GetPolicy(ctx context.Context, request GetPolicyRequestObject) (GetPolicyResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListEvaluations operation middleware
func (sh *strictHandler) ListEvaluations(w http.ResponseWriter, r *http.Request, params ListEvaluationsParams) {
	var request ListEvaluationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEvaluations(ctx, request.(ListEvaluationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEvaluations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEvaluationsResponseObject); ok {
		if err := validResponse.VisitListEvaluationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEvaluation operation middleware
func (sh *strictHandler) CreateEvaluation(w http.ResponseWriter, r *http.Request, params CreateEvaluationParams) {
	var request CreateEvaluationRequestObject

	request.Params = params

	var body CreateEvaluationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvaluation(ctx, request.(CreateEvaluationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvaluation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEvaluationResponseObject); ok {
		if err := validResponse.VisitCreateEvaluationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEvaluation operation middleware
func (sh *strictHandler) GetEvaluation(w http.ResponseWriter, r *http.Request, evaluationId EvaluationID) {
	var request GetEvaluationRequestObject

	request.EvaluationId = evaluationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEvaluation(ctx, request.(GetEvaluationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEvaluation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEvaluationResponseObject); ok {
		if err := validResponse.VisitGetEvaluationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitFeedback operation middleware
func (sh *strictHandler) SubmitFeedback(w http.ResponseWriter, r *http.Request, evaluationId EvaluationID) {
	var request SubmitFeedbackRequestObject

	request.EvaluationId = evaluationId

	var body SubmitFeedbackJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitFeedback(ctx, request.(SubmitFeedbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitFeedback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitFeedbackResponseObject); ok {
		if err := validResponse.VisitSubmitFeedbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPolicies operation middleware
func (sh *strictHandler) ListPolicies(w http.ResponseWriter, r *http.Request) {
	var request ListPoliciesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPolicies(ctx, request.(ListPoliciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPolicies")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPoliciesResponseObject); ok {
		if err := validResponse.VisitListPoliciesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ValidatePolicy operation middleware
func (sh *strictHandler) ValidatePolicy(w http.ResponseWriter, r *http.Request) {
	var request ValidatePolicyRequestObject

	var body ValidatePolicyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ValidatePolicy(ctx, request.(ValidatePolicyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ValidatePolicy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ValidatePolicyResponseObject); ok {
		if err := validResponse.VisitValidatePolicyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPolicy operation middleware
func (sh *strictHandler) GetPolicy(w http.ResponseWriter, r *http.Request, policyName string, policyVersion string) {
	var request GetPolicyRequestObject

	request.PolicyName = policyName
	request.PolicyVersion = policyVersion

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPolicy(ctx, request.(GetPolicyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPolicy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPolicyResponseObject); ok {
		if err := validResponse.VisitGetPolicyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Ftbbxu5kv4rRO8C+yLLl0kCrN48iXPGO0nGG9s5C2SCmGKX1EzYZA8vtrWB/vuiSPadujhxjFmcN7Wa",
	"l2JV8auqj+xvGVNlpSRIa7LZt6yimpZgQfuns1sqHLVcyfNX+MxlNssqaotskklaQjbLoG2SZ5NMw1+O",
	"a8izmdUOJplhBZQU+y6ULqnNZplzHFvaVYX9jdVcLrP1epKd51BWyoJkq99hhX1yMEzzCkfPZtkpYVQI",
	"0AesUAYkub4+f0VsQS0p6VcwxBbcEBQAjCUaKkFXdC5gmk2C4AXQHHQreme+A5zwYdK+4SW3jVL+cqBX",
	"7dDCv+wOmMOCOmGz2fOjSVbSe166MpudHOETl+HpuJmHSwtL0H6iPxYLAxtnUuFtcqru2EeJsddoL1Mp",
	"acCb+1ea/4NauKNe+UxJC9JPTKtKcOatfPjFoDG+deb7dw2LbJb922HrSofhrTk801rFqfrGvCqAVFrd",
	"8hw00WCdlpATo0qwBZdL8oHPgRXAvhKmnMiJVJY4A9NsPUE53wczP42ctU/dUUNKKtA3IPeSvFRyITh7",
	"Ijl467DkK6y8PBqcgZzccVsQSnK+WIAGaWuZvZTRqFe8BOXsE9s258F4VJo70IRLYnkZ7HguLWhJxSXo",
	"W9BhuJ8uXOtYC8pFtOM7ZV8rJ/OfP/07RYxjBdFglNMsKOKCroSi+ZVSb6hewtNYaK7yFYF7BpBDTmwB",
	"hCm54EunIScMuOBy6aVD83AG15LeUi4QUp/YhdDPndRAWYGzE6WJcpaoBWG0oozblZfzSqm3VK4iNJin",
	"ETKEpI161NQC8dHAi3gtqbOF0vx/IX8iKwPVoIlVX0EGAOPGIMAqTe60iia+lpVWDIxB/Z5Jy+3q6aH1",
	"DoQ4COBK5s7G/ek1WinB2QoVazVlqMt1HfG8nU89uIxThj8kEAx7eYSfKflnwVlBFhxEbgjV6GVgEDBz",
	"qEDmhihJbrDLzYxQIpUThFGtOeAbsSI3+NfNhFDCCsUZNG9vwvPNhNx4++cg/ROVObmptJrTORfccjDx",
	"T0oMU7ozgH8c9U/2vRGwBJnfYG5TaVWBxpfeZF4K/DVIWSZZO2wvw8mVwy3dyUqOk3mDdOUc04ZJFib3",
	"XpHnHFVNxUVHipD6jY2dAxMUd0VcuOYWNKcYy9DkKyJdCZozIuAWxLRNu9T8CzCLU6P2f1D6nj43LyI1",
	"x2iskXx+ZQ/qvH3z/DfuDq7kFbYNCVudYH8MA3xKSPFSA7XQZu+dbKnvLQvKrHmgIbUzFm1otWPWgxzO",
	"4/NvNLEFjeo3ljOinQBMUWieNCaXgku48Hv7YUKcEtSVANtAQ66YK0HaKXkPC58SOSnA1FJVQq3wNQGJ",
	"EGdImDv05mCm5NwSboiEWww4mlsLkljVRZ+ca2BW6VVyMSVYmlNLt3lUSe/fgFzaIpudPH8xGW/R/ip/",
	"xZQEg3GIMfUMRANTOq+zPpSwrcKSsoUFvEc32+5uF01D9GVLLYwx9SpEOAwMqKAvLl8C4mFYBcYVOnKO",
	"6ch3w+Ap523ywPG0gK8IyFsQqsJVg175MOE0YHVgpgieOdygKY31ycL1xcXZ+8+X705/P/v88vTyzOMn",
	"D37hZUMoFxxXY+64ZYVH+gSwqjwNqzlYygW28V5gDF2mGg7W74dr2ycV0Rh1vHFDONsKX9vsHONlCsGY",
	"x4781PZRjFo4wMQ9S3gt3ANzKMIFRdfekQ70Gq8nWbTfy6jfsdWjIYPxmaDGkLsCJP5vnfG7VtkGEDpQ",
	"87GWcZJJJ0T2CTEn36O8x2iCnpC/dwLO87RYCG6BfjAggNmYqihnmSphQnDKIGiAIF+UE59H7RJyHywZ",
	"iTyyZJQk2bhqQHdvOAhdfqOmGOvj8rfTg5PnLzAl93B0T5mtYdOrKAfGQ3rMTRqthrL9zkOKsVs+3zIE",
	"dl8vnFoLZWW7Wmo4j7bVK6e9CG83tIuZabD+SMb4FvK3KgexoYlR4rbTYuxCt6ANVxJyUmKjoCrKrKNC",
	"rGLK2vWVzujB+XdutkbTl6E9+omyVOxavatRbNvo177RENn8hor+1fOanmWbFbR+OgSSSYNytTxddNqO",
	"mG94SHcG5YAny0hFl1z6ZjVvUlDzVvliQM0Bi7YCa6aCSgwOykk7IXNg1BkYhFsSsGmp1Z3xg2FhOse4",
	"PY4gcZKOwudKCaDS50IWSt+q+bGfXTs7n2pNVz4/r6nJsV1VQyYmmMaeFb0Yk4bJbHjGehXb9X/ZuCdI",
	"TMQ/Zg0+Z+0e/BxKPM8bf/EQ2hm29fWzYXzpW/U3dUcWVA8ts1SWzGGBZqWyhmVfaNZ4PcXiCj4jkN+Q",
	"Eqg0hCYy2Aa8uPXJg1QtNYGpWeQFc88018utB84wQWAct3n7HPjZ1FJfA+Rzyr6OI/73xOUuN79P1IP7",
	"yivmjy2RY88AKpXdIwvyfQdHCEMhdm36tn7oK6xWe4jh/b21KXg2WyjaaJsiek6YeF/ESDnOLTaGjMDp",
	"J16oKqQAr7fXaw/ICh6oj0rDd+nxr1i/7g9twZx13Zsas3agR1AGvmL2XFbOpmE5RujdnuxN17aP5u+o",
	"e+RTXeVs9us6DapxBefJs7p2TmJI6FhHwP6meFiYiVtrZINkrNi8hsaYY1DzbNXLSATt4gDGBEI6OeMy",
	"1J+13w2SgLiXOgVrp1y9WlVwSRdAuoNMa+rpuyX1vFC3d63/hH//MC/UIvJAF5tNFLmBvnVqOOrQFi+e",
	"JRyus0k6TX85mTxsz2yW7gMVPN9QCUOaLvhnsQp1V+SFGjZZ+UqRh3PhzSXYQwokrwMUMYUhgzWHdqml",
	"9kzaTZwCo1tzi5EDTW38Szcvua1TiI2kXyLK77JwHc27BNbR0dEuAw9nSi37uq40BkCFmHylvoLcUKEo",
	"Z7e2GO6JzniDzimposdBvTs2qLL6Du7yqhiRlkmvbKQZrCTOOZZ67aFvoRK1pj8C8dQJX8RTnIln4blc",
	"hhOFOlsiJpz2kbnjwhIlW0T8L7id/inrWxjEeG/zPJsFUglniI3csKeVJzHPxqS6LXSD9GHOJVhD0FX9",
	"Tm1YlIZBSRPKA86F20kkArsHPaGwQ/F6dP8kFto4ezgS84VlcyATmaa2iDh/Nf1TtkfG3BCa33Kj9Moz",
	"xoEuDmVrZMCpx1qsFTwzaqbkTC6UZhhqrD/xincd6ookcpFBq/9hyBc1r+WJmsYhMVBJX55EPL+Fjs0K",
	"f0cCIY4wofyFgAIk6Qnu2vPbqS/sGEjjdx7PQVq+4KCzWfb2/Kq9XYIPGJG4FdA9O++g9iw7mj6bHoUs",
	"FSSteDbLfpkeT4+w0KO28BvlsNWpf15Cojx/B3dgLFlwbewkRW6T81eEmtZQlsNcA/0KGleE266pdjLM",
	"f846k056d5s+pnG9bXIY7vesJzsbxvs52DJ1QSc4/LsQ6toT0+2Iu32wD02SmRwvGXg33B5qctEflaxh",
	"c/Y8FB4RU+tPg9tIJ0dHj3cG3SeGEofRp6SiSyBq0XG3kPc9C3Kkhm/kPexcSfJdjnd36d0FWE+y5/vM",
	"k7oy48/CXVlSvYp+354QQW8HWLo0Pi53/g3JTootu1xJVmgllUMQu6fMihVR0iupOVHC9Ll7jkdKZyyZ",
	"AzEuMt3kvH/U5k/d9V6HdLaAcvqnvMShVgiBVJLBrb140S8MoTRfckztO5DRMPCMSiU5o6K5dMANCdDH",
	"qAiQy+J9rnjCwG08XRjDy/CI9cH4MrjtGNzfy/Wryh/v9sWmo+B1P63ARGU92oDHP2EDbroJ0jFZQxV6",
	"m4RbbsGfn3RDPjt6trtTc3PMd/jP3R2aK4PY4fiX3R2Gl8Ow38nJPssZ3+nxffcQcniV6ofgCfue7GWx",
	"+vap77KHahI303zXPew2uBPZx9DorRBzW7qkWEYTSppjjTSSrie9ROfwW5faXHfynj6W/APsDwBJ75L2",
	"E0XR3Zv4771THynWvgbLCh8SoWu/73GOw0WX+U/G47qwx5jEqODz4EIkp5Z2qhFWULnEMNtmAU2h4I8v",
	"fCsuF8KBZL7hwlmnARcyDnR9UuExvPPxg1ya+HjiENeoaMPeqA38/ymg/UCceaQt9t4rqnuzglBSuJJK",
	"UrNLW3dcnXVuBF/Mly/qRj8RPDusfMJBzjyDEWkhDPeY/FiMP9q6avq3KCqiWFWrrFrtzV99nR/eRhZt",
	"M6a9DKxXSN/rkqHlxRCvNFRKh4zcH8uHpNwPPSXvVPhchJtdl/bi0W3TPKxmjHd95i/7OYCVphf3AqzH",
	"9sgOt77pinuwEdFgnLCToHqs+3xh9JT49Z3p8iNtguirTRrYuml98QOzRCqE9zC7x/741pJD68NIqDX/",
	"RpZna9rYOOkgKCc+1OvxUJs/09uT/UmN3dJSew2foqk+/XR33/ixiX/7L5a1dhF9tcFfsasfKnjW4GOq",
	"YHJyXN/8q9xccEZOL84RWZ0W2Sw7vD32mV8cfUQz+eQtXMuVBkN6k6+aaepDU+O51v4g57EnjlJHnWHA",
	"mg4cFheIct0fMIUbN34Cy6XtfEWJkS9+6hm/3Oz8Ez7fpPdv433NM2m1zzWOX/T+/0CFg97N75Lev1MW",
	"uodp8TqCXPq7Yv5b1eEXsYlPVkPD6Irnr7JZ9j8H8enAX6dBvXwYcvXr9f8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
