// Code generated by oapixconstgen. DO NOT EDIT.

package api

const (
	DefaultListLimit       int    = 50
	HeaderIdempotencyKey   string = "Idempotency-Key"
	HeaderRequestID        string = "X-Request-Id"
	MaxListLimit           int    = 200
	MaxMetadataEntries     int    = 16
	MaxMetadataValueLength int    = 256
	MaxNoteLength          int    = 2000
	SpecVersion            string = "0.2.0"
)
