// Code generated by service_registration.sh; DO NOT EDIT.

package services

import (
	servicemanager "github.com/psyb0t/vibecheck/internal/pkg/service-manager"
	vibecheckserver "github.com/psyb0t/vibecheck/internal/pkg/services/vibecheck-server"
)

func Init() {
	sm := servicemanager.GetInstance()

	sm.Register(vibecheckserver.ServiceName, func() (servicemanager.Service, error) {
		return vibecheckserver.New()
	})

}
