// Code generated by service_registration.sh; DO NOT EDIT.

package services

import (
	servicemanager "github.com/psyb0t/vibecheck/internal/pkg/service-manager"
	helloworld "github.com/psyb0t/vibecheck/internal/pkg/services/hello-world"
)

func Init() {
	sm := servicemanager.GetInstance()

	sm.Register(helloworld.ServiceName, func() (servicemanager.Service, error) {
		return helloworld.New()
	})

}
