// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/psyb0t/vibecheck/pkg/gotypesafe"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type MockClient
func (_mock *MockClient) Evaluate(ctx context.Context, request typesafe.Request) (typesafe.Response, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 typesafe.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, typesafe.Request) (typesafe.Response, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, typesafe.Request) typesafe.Response); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(typesafe.Response)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, typesafe.Request) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockClient_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - request typesafe.Request
func (_e *MockClient_Expecter) Evaluate(ctx interface{}, request interface{}) *MockClient_Evaluate_Call {
	return &MockClient_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, request)}
}

func (_c *MockClient_Evaluate_Call) Run(run func(ctx context.Context, request typesafe.Request)) *MockClient_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 typesafe.Request
		if args[1] != nil {
			arg1 = args[1].(typesafe.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Evaluate_Call) Return(response typesafe.Response, err error) *MockClient_Evaluate_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockClient_Evaluate_Call) RunAndReturn(run func(ctx context.Context, request typesafe.Request) (typesafe.Response, error)) *MockClient_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// Models provides a mock function for the type MockClient
func (_mock *MockClient) Models(ctx context.Context) ([]typesafe.ModelMetadata, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Models")
	}

	var r0 []typesafe.ModelMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]typesafe.ModelMetadata, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []typesafe.ModelMetadata); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]typesafe.ModelMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Models_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Models'
type MockClient_Models_Call struct {
	*mock.Call
}

// Models is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Models(ctx interface{}) *MockClient_Models_Call {
	return &MockClient_Models_Call{Call: _e.mock.On("Models", ctx)}
}

func (_c *MockClient_Models_Call) Run(run func(ctx context.Context)) *MockClient_Models_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Models_Call) Return(modelMetadatas []typesafe.ModelMetadata, err error) *MockClient_Models_Call {
	_c.Call.Return(modelMetadatas, err)
	return _c
}

func (_c *MockClient_Models_Call) RunAndReturn(run func(ctx context.Context) ([]typesafe.ModelMetadata, error)) *MockClient_Models_Call {
	_c.Call.Return(run)
	return _c
}
