// Package typesafe provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package typesafe

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ChoiceAnswerType.
const (
	ChoiceAnswerTypeChoice ChoiceAnswerType = "choice"
)

// Valid indicates whether the value is a known member of the ChoiceAnswerType enum.
func (e ChoiceAnswerType) Valid() bool {
	switch e {
	case ChoiceAnswerTypeChoice:
		return true
	default:
		return false
	}
}

// Defines values for ChoiceQuestionType.
const (
	ChoiceQuestionTypeChoice ChoiceQuestionType = "choice"
)

// Valid indicates whether the value is a known member of the ChoiceQuestionType enum.
func (e ChoiceQuestionType) Valid() bool {
	switch e {
	case ChoiceQuestionTypeChoice:
		return true
	default:
		return false
	}
}

// Defines values for NoulAnswerType.
const (
	NoulAnswerTypeNoul NoulAnswerType = "noul"
)

// Valid indicates whether the value is a known member of the NoulAnswerType enum.
func (e NoulAnswerType) Valid() bool {
	switch e {
	case NoulAnswerTypeNoul:
		return true
	default:
		return false
	}
}

// Defines values for NoulQuestionType.
const (
	NoulQuestionTypeNoul NoulQuestionType = "noul"
)

// Valid indicates whether the value is a known member of the NoulQuestionType enum.
func (e NoulQuestionType) Valid() bool {
	switch e {
	case NoulQuestionTypeNoul:
		return true
	default:
		return false
	}
}

// Defines values for ScoreAnswerType.
const (
	ScoreAnswerTypeScore ScoreAnswerType = "score"
)

// Valid indicates whether the value is a known member of the ScoreAnswerType enum.
func (e ScoreAnswerType) Valid() bool {
	switch e {
	case ScoreAnswerTypeScore:
		return true
	default:
		return false
	}
}

// Defines values for ScoreQuestionType.
const (
	ScoreQuestionTypeScore ScoreQuestionType = "score"
)

// Valid indicates whether the value is a known member of the ScoreQuestionType enum.
func (e ScoreQuestionType) Valid() bool {
	switch e {
	case ScoreQuestionTypeScore:
		return true
	default:
		return false
	}
}

// Answer An answer whose type matches the corresponding question.
type Answer struct {
	union json.RawMessage
}

// ChoiceAnswer The selected choice, confidence, and probabilities for a choice question.
type ChoiceAnswer struct {
	// Choice The name of the choice with the highest probability among the question's criteria.
	//
	// Examples: angry
	Choice string `json:"choice"`

	// Confidence Confidence in the selected choice, from 0 to 1. Higher values indicate greater certainty; use lower values to flag uncertain selections for review.
	//
	// Examples: 0.9
	Confidence float32 `json:"confidence"`

	// Probabilities Probability of each choice in criteria, keyed by choice name, from 0 to 1. Shows how likely the alternatives are; values sum to approximately 1.
	//
	// Examples: {"angry":0.8,"calm":0.1,"excited":0.1}
	Probabilities map[string]float32 `json:"probabilities"`

	// Type Identifies a selection from the requested choices.
	//
	// Examples: choice
	Type ChoiceAnswerType `json:"type"`
}

// ChoiceAnswerType Identifies a selection from the requested choices.
//
// Examples: choice
type ChoiceAnswerType string

// ChoiceQuestion A question that selects one option from the choices you define.
type ChoiceQuestion struct {
	// Criteria Choice names and descriptions of when each applies. A choice without a description is interpreted by its name alone.
	//
	// Examples: {"angry":"An upset or hostile message","calm":"A neutral or polite message","excited":"An enthusiastic or eager message"}
	Criteria map[string]*ChoiceQuestion_Criteria_AdditionalProperties `json:"criteria"`

	// Instructions What the model should decide when choosing an option.
	//
	// Examples: What is the tone of this message?
	Instructions *ChoiceQuestion_Instructions `json:"instructions,omitempty"`

	// Type Identifies a question that selects one of the choices in criteria.
	//
	// Examples: choice
	Type ChoiceQuestionType `json:"type"`
}

// ChoiceQuestionCriteria0 defines model for ChoiceQuestion.Criteria.0.
type ChoiceQuestionCriteria0 = string

// ChoiceQuestionCriteria1 defines model for ChoiceQuestion.Criteria.1.
type ChoiceQuestionCriteria1 map[string]interface{}

// ChoiceQuestionCriteria2 defines model for ChoiceQuestion.Criteria.2.
type ChoiceQuestionCriteria2 = []interface{}

// ChoiceQuestion_Criteria_AdditionalProperties defines model for ChoiceQuestion.criteria.AdditionalProperties.
type ChoiceQuestion_Criteria_AdditionalProperties struct {
	union json.RawMessage
}

// ChoiceQuestionInstructions0 defines model for ChoiceQuestion.Instructions.0.
type ChoiceQuestionInstructions0 = string

// ChoiceQuestionInstructions1 defines model for ChoiceQuestion.Instructions.1.
type ChoiceQuestionInstructions1 map[string]interface{}

// ChoiceQuestionInstructions2 defines model for ChoiceQuestion.Instructions.2.
type ChoiceQuestionInstructions2 = []interface{}

// ChoiceQuestion_Instructions What the model should decide when choosing an option.
//
// Examples: What is the tone of this message?
type ChoiceQuestion_Instructions struct {
	union json.RawMessage
}

// ChoiceQuestionType Identifies a question that selects one of the choices in criteria.
//
// Examples: choice
type ChoiceQuestionType string

// HTTPValidationError Request validation failures returned with HTTP status 422.
type HTTPValidationError struct {
	// Detail Validation errors describing which request values are missing or invalid.
	//
	// Examples: [{"loc":["body","state"],"msg":"Field required","type":"missing"}]
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// ModelMetadata A model or model alias available to the authenticated account.
type ModelMetadata struct {
	// Description Human-readable description of the model and its capabilities.
	//
	// Examples: General-purpose system one model.
	Description string `json:"description"`

	// Name Model name or alias accepted by the request's model field.
	//
	// Examples: jev-latest
	Name string `json:"name"`

	// ReleaseDate Model release date, formatted as YYYY-MM-DD.
	//
	// Examples: 2026-09-15
	ReleaseDate string `json:"release_date"`
}

// ModelMetadataList Models and aliases available to the authenticated account.
type ModelMetadataList struct {
	// Models Available models and aliases. Use a model's name in POST /v1/systemone requests.
	//
	// Examples: [{"description":"General-purpose system one model.","name":"jev-latest","release_date":"2026-09-15"}]
	Models []ModelMetadata `json:"models"`
}

// NoulAnswer The probability of a yes answer or a true statement.
type NoulAnswer struct {
	// Noul Probability of a yes answer or a true statement, from 0 to 1. Values near 1 favor yes or true, values near 0 favor no or false, and values near 0.5 indicate uncertainty.
	//
	// Examples: 0.98
	Noul float32 `json:"noul"`

	// Type Identifies a yes/no answer.
	//
	// Examples: noul
	Type NoulAnswerType `json:"type"`
}

// NoulAnswerType Identifies a yes/no answer.
//
// Examples: noul
type NoulAnswerType string

// NoulCriteria Criteria defining what counts as a yes or no answer.
type NoulCriteria struct {
	// False What counts as a no answer.
	//
	// Examples: The message is a legitimate conversation.
	False *NoulCriteria_False `json:"false,omitempty"`

	// True What counts as a yes answer.
	//
	// Examples: The message is unsolicited advertising.
	True *NoulCriteria_True `json:"true,omitempty"`
}

// NoulCriteriaFalse0 defines model for NoulCriteria.False.0.
type NoulCriteriaFalse0 = string

// NoulCriteriaFalse1 defines model for NoulCriteria.False.1.
type NoulCriteriaFalse1 map[string]interface{}

// NoulCriteriaFalse2 defines model for NoulCriteria.False.2.
type NoulCriteriaFalse2 = []interface{}

// NoulCriteria_False What counts as a no answer.
//
// Examples: The message is a legitimate conversation.
type NoulCriteria_False struct {
	union json.RawMessage
}

// NoulCriteriaTrue0 defines model for NoulCriteria.True.0.
type NoulCriteriaTrue0 = string

// NoulCriteriaTrue1 defines model for NoulCriteria.True.1.
type NoulCriteriaTrue1 map[string]interface{}

// NoulCriteriaTrue2 defines model for NoulCriteria.True.2.
type NoulCriteriaTrue2 = []interface{}

// NoulCriteria_True What counts as a yes answer.
//
// Examples: The message is unsolicited advertising.
type NoulCriteria_True struct {
	union json.RawMessage
}

// NoulQuestion A yes/no question or statement, answered with the probability of yes or true.
type NoulQuestion struct {
	// Criteria Criteria clarifying what counts as a yes or no answer.
	//
	// Examples: {"false":"A legitimate conversation","true":"Unsolicited advertising"}
	Criteria *NoulCriteria `json:"criteria,omitempty"`

	// Instructions The yes/no question or statement to evaluate.
	//
	// Examples: Is this message spam?, This message contains unsolicited advertising., {"task":"Identify unsolicited advertising."}
	Instructions *NoulQuestion_Instructions `json:"instructions,omitempty"`

	// Type Identifies a yes/no question or statement.
	//
	// Examples: noul
	Type NoulQuestionType `json:"type"`
}

// NoulQuestionInstructions0 defines model for NoulQuestion.Instructions.0.
type NoulQuestionInstructions0 = string

// NoulQuestionInstructions1 defines model for NoulQuestion.Instructions.1.
type NoulQuestionInstructions1 map[string]interface{}

// NoulQuestionInstructions2 defines model for NoulQuestion.Instructions.2.
type NoulQuestionInstructions2 = []interface{}

// NoulQuestion_Instructions The yes/no question or statement to evaluate.
//
// Examples: Is this message spam?, This message contains unsolicited advertising., {"task":"Identify unsolicited advertising."}
type NoulQuestion_Instructions struct {
	union json.RawMessage
}

// NoulQuestionType Identifies a yes/no question or statement.
//
// Examples: noul
type NoulQuestionType string

// Question A question about the supplied content.
type Question struct {
	union json.RawMessage
}

// ScoreAnswer An expected score with its rubric, confidence, and score-level probabilities.
type ScoreAnswer struct {
	// Confidence Confidence in the score, from 0 to 1. Higher values indicate greater certainty; use lower values to flag uncertain ratings for review.
	//
	// Examples: 0.9
	Confidence float32 `json:"confidence"`

	// Legend The requested criteria mapped to their score levels, so you can interpret the score.
	//
	// Examples: {"0":"Can wait","1":"Needs attention this week","2":"Needs attention today"}
	Legend map[string]ScoreAnswer_Legend_AdditionalProperties `json:"legend"`

	// Probabilities Probability of each score level, from 0 to 1, using the same keys as legend. Shows how likely the alternatives are; values sum to approximately 1.
	//
	// Examples: {"0":0.1,"1":0.1,"2":0.8}
	Probabilities map[string]float32 `json:"probabilities"`

	// Score Expected score: the probability-weighted average of the rubric levels. May fall between integer levels.
	//
	// Examples: 1.7
	Score float32 `json:"score"`

	// Type Identifies a rating against the requested score levels.
	//
	// Examples: score
	Type ScoreAnswerType `json:"type"`
}

// ScoreAnswerLegend0 defines model for ScoreAnswer.Legend.0.
type ScoreAnswerLegend0 = string

// ScoreAnswerLegend1 defines model for ScoreAnswer.Legend.1.
type ScoreAnswerLegend1 map[string]interface{}

// ScoreAnswerLegend2 defines model for ScoreAnswer.Legend.2.
type ScoreAnswerLegend2 = []interface{}

// ScoreAnswer_Legend_AdditionalProperties defines model for ScoreAnswer.legend.AdditionalProperties.
type ScoreAnswer_Legend_AdditionalProperties struct {
	union json.RawMessage
}

// ScoreAnswerType Identifies a rating against the requested score levels.
//
// Examples: score
type ScoreAnswerType string

// ScoreQuestion A question that assigns a score using an ordered rubric.
type ScoreQuestion struct {
	// Criteria Ordered descriptions of the score levels. Each description's position determines its score, starting at zero.
	//
	// Examples: ["Can wait","Needs attention this week","Needs attention today"]
	Criteria []ScoreQuestion_Criteria_Item `json:"criteria"`

	// Instructions What the model should rate.
	//
	// Examples: How urgent is this message?
	Instructions *ScoreQuestion_Instructions `json:"instructions,omitempty"`

	// Type Identifies a question that rates the content using the levels in criteria.
	//
	// Examples: score
	Type ScoreQuestionType `json:"type"`
}

// ScoreQuestionCriteria0 defines model for ScoreQuestion.Criteria.0.
type ScoreQuestionCriteria0 = string

// ScoreQuestionCriteria1 defines model for ScoreQuestion.Criteria.1.
type ScoreQuestionCriteria1 map[string]interface{}

// ScoreQuestionCriteria2 defines model for ScoreQuestion.Criteria.2.
type ScoreQuestionCriteria2 = []interface{}

// ScoreQuestion_Criteria_Item defines model for ScoreQuestion.criteria.Item.
type ScoreQuestion_Criteria_Item struct {
	union json.RawMessage
}

// ScoreQuestionInstructions0 defines model for ScoreQuestion.Instructions.0.
type ScoreQuestionInstructions0 = string

// ScoreQuestionInstructions1 defines model for ScoreQuestion.Instructions.1.
type ScoreQuestionInstructions1 map[string]interface{}

// ScoreQuestionInstructions2 defines model for ScoreQuestion.Instructions.2.
type ScoreQuestionInstructions2 = []interface{}

// ScoreQuestion_Instructions What the model should rate.
//
// Examples: How urgent is this message?
type ScoreQuestion_Instructions struct {
	union json.RawMessage
}

// ScoreQuestionType Identifies a question that rates the content using the levels in criteria.
//
// Examples: score
type ScoreQuestionType string

// SystemOneRequest Content and named questions to evaluate together using a TypeSafe model.
type SystemOneRequest struct {
	// Model Name or alias of the model to use. Available names are returned by GET /v1/models.
	//
	// Examples: jev-latest
	Model string `json:"model"`

	// Questions Questions to ask about the content, each with a name you choose. The response uses those names to identify the answers.
	//
	// Examples: {"billing":{"instructions":"Is this message about billing?","type":"noul"}}
	Questions map[string]Question `json:"questions"`

	// State The content all questions in this request refer to.
	//
	// Examples: I was charged twice. Please help., {"message":"Please help.","subject":"Duplicate charge"}
	State SystemOneRequest_State `json:"state"`
}

// SystemOneRequestState0 defines model for SystemOneRequest.State.0.
type SystemOneRequestState0 = string

// SystemOneRequestState1 defines model for SystemOneRequest.State.1.
type SystemOneRequestState1 map[string]interface{}

// SystemOneRequestState2 defines model for SystemOneRequest.State.2.
type SystemOneRequestState2 = []interface{}

// SystemOneRequest_State The content all questions in this request refer to.
//
// Examples: I was charged twice. Please help., {"message":"Please help.","subject":"Duplicate charge"}
type SystemOneRequest_State struct {
	union json.RawMessage
}

// SystemOneResponse Answers grouped by question name, with the model used and token usage.
type SystemOneResponse struct {
	// Answers Answers keyed by the question names supplied in the request. Each answer's type matches its question's type.
	//
	// Examples: {"billing":{"noul":0.98,"type":"noul"}}
	Answers map[string]Answer `json:"answers"`

	// Model Name of the model that answered the questions. May differ from the alias supplied in the request.
	//
	// Examples: jev-latest
	Model string `json:"model"`

	// Usage Input and output token counts for this evaluation.
	//
	// Examples: {"input_tokens":120,"output_tokens":12}
	Usage Usage `json:"usage"`
}

// Usage Token usage for the request.
type Usage struct {
	// InputTokens Number of billable input tokens used to evaluate the request.
	//
	// Examples: 120
	InputTokens int `json:"input_tokens"`

	// OutputTokens Number of output tokens used to answer the questions. Output tokens are currently free of charge.
	//
	// Examples: 12
	OutputTokens int `json:"output_tokens"`
}

// ValidationError A request validation error at a specific field or array element.
type ValidationError struct {
	// Ctx Additional context used to explain the validation failure.
	//
	// Examples: {"min_length":1}
	Ctx *map[string]interface{} `json:"ctx,omitempty"`

	// Input The input value that failed validation.
	//
	// Examples: {"type":"score"}
	Input interface{} `json:"input,omitempty"`

	// Loc Path to the invalid value: the request location followed by field names and array indices.
	//
	// Examples: ["body","questions","urgency","score","criteria"]
	Loc []ValidationError_Loc_Item `json:"loc"`

	// Msg Human-readable explanation of the validation failure.
	//
	// Examples: Field required
	Msg string `json:"msg"`

	// Type Machine-readable validation error code.
	//
	// Examples: missing
	Type string `json:"type"`
}

// ValidationErrorLoc0 defines model for ValidationError.Loc.0.
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for ValidationError.Loc.1.
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// SystemoneV1SystemonePostJSONRequestBody defines body for SystemoneV1SystemonePost for application/json ContentType.
type SystemoneV1SystemonePostJSONRequestBody = SystemOneRequest

// AsNoulAnswer returns the union data inside the Answer as a NoulAnswer
func (t Answer) AsNoulAnswer() (NoulAnswer, error) {
	var body NoulAnswer
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulAnswer overwrites any union data inside the Answer as the provided NoulAnswer
func (t *Answer) FromNoulAnswer(v NoulAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"noul"}`))
	t.union = b
	return err
}

// MergeNoulAnswer performs a merge with any union data inside the Answer, using the provided NoulAnswer
func (t *Answer) MergeNoulAnswer(v NoulAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"noul"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreAnswer returns the union data inside the Answer as a ScoreAnswer
func (t Answer) AsScoreAnswer() (ScoreAnswer, error) {
	var body ScoreAnswer
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreAnswer overwrites any union data inside the Answer as the provided ScoreAnswer
func (t *Answer) FromScoreAnswer(v ScoreAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"score"}`))
	t.union = b
	return err
}

// MergeScoreAnswer performs a merge with any union data inside the Answer, using the provided ScoreAnswer
func (t *Answer) MergeScoreAnswer(v ScoreAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"score"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChoiceAnswer returns the union data inside the Answer as a ChoiceAnswer
func (t Answer) AsChoiceAnswer() (ChoiceAnswer, error) {
	var body ChoiceAnswer
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceAnswer overwrites any union data inside the Answer as the provided ChoiceAnswer
func (t *Answer) FromChoiceAnswer(v ChoiceAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"choice"}`))
	t.union = b
	return err
}

// MergeChoiceAnswer performs a merge with any union data inside the Answer, using the provided ChoiceAnswer
func (t *Answer) MergeChoiceAnswer(v ChoiceAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"choice"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Answer) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Answer) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "choice":
		return t.AsChoiceAnswer()
	case "noul":
		return t.AsNoulAnswer()
	case "score":
		return t.AsScoreAnswer()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Answer) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Answer) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsChoiceQuestionCriteria0 returns the union data inside the ChoiceQuestion_Criteria_AdditionalProperties as a ChoiceQuestionCriteria0
func (t ChoiceQuestion_Criteria_AdditionalProperties) AsChoiceQuestionCriteria0() (ChoiceQuestionCriteria0, error) {
	var body ChoiceQuestionCriteria0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceQuestionCriteria0 overwrites any union data inside the ChoiceQuestion_Criteria_AdditionalProperties as the provided ChoiceQuestionCriteria0
func (t *ChoiceQuestion_Criteria_AdditionalProperties) FromChoiceQuestionCriteria0(v ChoiceQuestionCriteria0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChoiceQuestionCriteria0 performs a merge with any union data inside the ChoiceQuestion_Criteria_AdditionalProperties, using the provided ChoiceQuestionCriteria0
func (t *ChoiceQuestion_Criteria_AdditionalProperties) MergeChoiceQuestionCriteria0(v ChoiceQuestionCriteria0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChoiceQuestionCriteria1 returns the union data inside the ChoiceQuestion_Criteria_AdditionalProperties as a ChoiceQuestionCriteria1
func (t ChoiceQuestion_Criteria_AdditionalProperties) AsChoiceQuestionCriteria1() (ChoiceQuestionCriteria1, error) {
	var body ChoiceQuestionCriteria1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceQuestionCriteria1 overwrites any union data inside the ChoiceQuestion_Criteria_AdditionalProperties as the provided ChoiceQuestionCriteria1
func (t *ChoiceQuestion_Criteria_AdditionalProperties) FromChoiceQuestionCriteria1(v ChoiceQuestionCriteria1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChoiceQuestionCriteria1 performs a merge with any union data inside the ChoiceQuestion_Criteria_AdditionalProperties, using the provided ChoiceQuestionCriteria1
func (t *ChoiceQuestion_Criteria_AdditionalProperties) MergeChoiceQuestionCriteria1(v ChoiceQuestionCriteria1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChoiceQuestionCriteria2 returns the union data inside the ChoiceQuestion_Criteria_AdditionalProperties as a ChoiceQuestionCriteria2
func (t ChoiceQuestion_Criteria_AdditionalProperties) AsChoiceQuestionCriteria2() (ChoiceQuestionCriteria2, error) {
	var body ChoiceQuestionCriteria2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceQuestionCriteria2 overwrites any union data inside the ChoiceQuestion_Criteria_AdditionalProperties as the provided ChoiceQuestionCriteria2
func (t *ChoiceQuestion_Criteria_AdditionalProperties) FromChoiceQuestionCriteria2(v ChoiceQuestionCriteria2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChoiceQuestionCriteria2 performs a merge with any union data inside the ChoiceQuestion_Criteria_AdditionalProperties, using the provided ChoiceQuestionCriteria2
func (t *ChoiceQuestion_Criteria_AdditionalProperties) MergeChoiceQuestionCriteria2(v ChoiceQuestionCriteria2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChoiceQuestion_Criteria_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChoiceQuestion_Criteria_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsChoiceQuestionInstructions0 returns the union data inside the ChoiceQuestion_Instructions as a ChoiceQuestionInstructions0
func (t ChoiceQuestion_Instructions) AsChoiceQuestionInstructions0() (ChoiceQuestionInstructions0, error) {
	var body ChoiceQuestionInstructions0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceQuestionInstructions0 overwrites any union data inside the ChoiceQuestion_Instructions as the provided ChoiceQuestionInstructions0
func (t *ChoiceQuestion_Instructions) FromChoiceQuestionInstructions0(v ChoiceQuestionInstructions0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChoiceQuestionInstructions0 performs a merge with any union data inside the ChoiceQuestion_Instructions, using the provided ChoiceQuestionInstructions0
func (t *ChoiceQuestion_Instructions) MergeChoiceQuestionInstructions0(v ChoiceQuestionInstructions0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChoiceQuestionInstructions1 returns the union data inside the ChoiceQuestion_Instructions as a ChoiceQuestionInstructions1
func (t ChoiceQuestion_Instructions) AsChoiceQuestionInstructions1() (ChoiceQuestionInstructions1, error) {
	var body ChoiceQuestionInstructions1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceQuestionInstructions1 overwrites any union data inside the ChoiceQuestion_Instructions as the provided ChoiceQuestionInstructions1
func (t *ChoiceQuestion_Instructions) FromChoiceQuestionInstructions1(v ChoiceQuestionInstructions1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChoiceQuestionInstructions1 performs a merge with any union data inside the ChoiceQuestion_Instructions, using the provided ChoiceQuestionInstructions1
func (t *ChoiceQuestion_Instructions) MergeChoiceQuestionInstructions1(v ChoiceQuestionInstructions1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChoiceQuestionInstructions2 returns the union data inside the ChoiceQuestion_Instructions as a ChoiceQuestionInstructions2
func (t ChoiceQuestion_Instructions) AsChoiceQuestionInstructions2() (ChoiceQuestionInstructions2, error) {
	var body ChoiceQuestionInstructions2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceQuestionInstructions2 overwrites any union data inside the ChoiceQuestion_Instructions as the provided ChoiceQuestionInstructions2
func (t *ChoiceQuestion_Instructions) FromChoiceQuestionInstructions2(v ChoiceQuestionInstructions2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChoiceQuestionInstructions2 performs a merge with any union data inside the ChoiceQuestion_Instructions, using the provided ChoiceQuestionInstructions2
func (t *ChoiceQuestion_Instructions) MergeChoiceQuestionInstructions2(v ChoiceQuestionInstructions2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChoiceQuestion_Instructions) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChoiceQuestion_Instructions) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNoulCriteriaFalse0 returns the union data inside the NoulCriteria_False as a NoulCriteriaFalse0
func (t NoulCriteria_False) AsNoulCriteriaFalse0() (NoulCriteriaFalse0, error) {
	var body NoulCriteriaFalse0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulCriteriaFalse0 overwrites any union data inside the NoulCriteria_False as the provided NoulCriteriaFalse0
func (t *NoulCriteria_False) FromNoulCriteriaFalse0(v NoulCriteriaFalse0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulCriteriaFalse0 performs a merge with any union data inside the NoulCriteria_False, using the provided NoulCriteriaFalse0
func (t *NoulCriteria_False) MergeNoulCriteriaFalse0(v NoulCriteriaFalse0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoulCriteriaFalse1 returns the union data inside the NoulCriteria_False as a NoulCriteriaFalse1
func (t NoulCriteria_False) AsNoulCriteriaFalse1() (NoulCriteriaFalse1, error) {
	var body NoulCriteriaFalse1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulCriteriaFalse1 overwrites any union data inside the NoulCriteria_False as the provided NoulCriteriaFalse1
func (t *NoulCriteria_False) FromNoulCriteriaFalse1(v NoulCriteriaFalse1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulCriteriaFalse1 performs a merge with any union data inside the NoulCriteria_False, using the provided NoulCriteriaFalse1
func (t *NoulCriteria_False) MergeNoulCriteriaFalse1(v NoulCriteriaFalse1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoulCriteriaFalse2 returns the union data inside the NoulCriteria_False as a NoulCriteriaFalse2
func (t NoulCriteria_False) AsNoulCriteriaFalse2() (NoulCriteriaFalse2, error) {
	var body NoulCriteriaFalse2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulCriteriaFalse2 overwrites any union data inside the NoulCriteria_False as the provided NoulCriteriaFalse2
func (t *NoulCriteria_False) FromNoulCriteriaFalse2(v NoulCriteriaFalse2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulCriteriaFalse2 performs a merge with any union data inside the NoulCriteria_False, using the provided NoulCriteriaFalse2
func (t *NoulCriteria_False) MergeNoulCriteriaFalse2(v NoulCriteriaFalse2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NoulCriteria_False) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NoulCriteria_False) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNoulCriteriaTrue0 returns the union data inside the NoulCriteria_True as a NoulCriteriaTrue0
func (t NoulCriteria_True) AsNoulCriteriaTrue0() (NoulCriteriaTrue0, error) {
	var body NoulCriteriaTrue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulCriteriaTrue0 overwrites any union data inside the NoulCriteria_True as the provided NoulCriteriaTrue0
func (t *NoulCriteria_True) FromNoulCriteriaTrue0(v NoulCriteriaTrue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulCriteriaTrue0 performs a merge with any union data inside the NoulCriteria_True, using the provided NoulCriteriaTrue0
func (t *NoulCriteria_True) MergeNoulCriteriaTrue0(v NoulCriteriaTrue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoulCriteriaTrue1 returns the union data inside the NoulCriteria_True as a NoulCriteriaTrue1
func (t NoulCriteria_True) AsNoulCriteriaTrue1() (NoulCriteriaTrue1, error) {
	var body NoulCriteriaTrue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulCriteriaTrue1 overwrites any union data inside the NoulCriteria_True as the provided NoulCriteriaTrue1
func (t *NoulCriteria_True) FromNoulCriteriaTrue1(v NoulCriteriaTrue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulCriteriaTrue1 performs a merge with any union data inside the NoulCriteria_True, using the provided NoulCriteriaTrue1
func (t *NoulCriteria_True) MergeNoulCriteriaTrue1(v NoulCriteriaTrue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoulCriteriaTrue2 returns the union data inside the NoulCriteria_True as a NoulCriteriaTrue2
func (t NoulCriteria_True) AsNoulCriteriaTrue2() (NoulCriteriaTrue2, error) {
	var body NoulCriteriaTrue2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulCriteriaTrue2 overwrites any union data inside the NoulCriteria_True as the provided NoulCriteriaTrue2
func (t *NoulCriteria_True) FromNoulCriteriaTrue2(v NoulCriteriaTrue2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulCriteriaTrue2 performs a merge with any union data inside the NoulCriteria_True, using the provided NoulCriteriaTrue2
func (t *NoulCriteria_True) MergeNoulCriteriaTrue2(v NoulCriteriaTrue2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NoulCriteria_True) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NoulCriteria_True) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNoulQuestionInstructions0 returns the union data inside the NoulQuestion_Instructions as a NoulQuestionInstructions0
func (t NoulQuestion_Instructions) AsNoulQuestionInstructions0() (NoulQuestionInstructions0, error) {
	var body NoulQuestionInstructions0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulQuestionInstructions0 overwrites any union data inside the NoulQuestion_Instructions as the provided NoulQuestionInstructions0
func (t *NoulQuestion_Instructions) FromNoulQuestionInstructions0(v NoulQuestionInstructions0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulQuestionInstructions0 performs a merge with any union data inside the NoulQuestion_Instructions, using the provided NoulQuestionInstructions0
func (t *NoulQuestion_Instructions) MergeNoulQuestionInstructions0(v NoulQuestionInstructions0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoulQuestionInstructions1 returns the union data inside the NoulQuestion_Instructions as a NoulQuestionInstructions1
func (t NoulQuestion_Instructions) AsNoulQuestionInstructions1() (NoulQuestionInstructions1, error) {
	var body NoulQuestionInstructions1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulQuestionInstructions1 overwrites any union data inside the NoulQuestion_Instructions as the provided NoulQuestionInstructions1
func (t *NoulQuestion_Instructions) FromNoulQuestionInstructions1(v NoulQuestionInstructions1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulQuestionInstructions1 performs a merge with any union data inside the NoulQuestion_Instructions, using the provided NoulQuestionInstructions1
func (t *NoulQuestion_Instructions) MergeNoulQuestionInstructions1(v NoulQuestionInstructions1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNoulQuestionInstructions2 returns the union data inside the NoulQuestion_Instructions as a NoulQuestionInstructions2
func (t NoulQuestion_Instructions) AsNoulQuestionInstructions2() (NoulQuestionInstructions2, error) {
	var body NoulQuestionInstructions2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulQuestionInstructions2 overwrites any union data inside the NoulQuestion_Instructions as the provided NoulQuestionInstructions2
func (t *NoulQuestion_Instructions) FromNoulQuestionInstructions2(v NoulQuestionInstructions2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoulQuestionInstructions2 performs a merge with any union data inside the NoulQuestion_Instructions, using the provided NoulQuestionInstructions2
func (t *NoulQuestion_Instructions) MergeNoulQuestionInstructions2(v NoulQuestionInstructions2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NoulQuestion_Instructions) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NoulQuestion_Instructions) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNoulQuestion returns the union data inside the Question as a NoulQuestion
func (t Question) AsNoulQuestion() (NoulQuestion, error) {
	var body NoulQuestion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulQuestion overwrites any union data inside the Question as the provided NoulQuestion
func (t *Question) FromNoulQuestion(v NoulQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"noul"}`))
	t.union = b
	return err
}

// MergeNoulQuestion performs a merge with any union data inside the Question, using the provided NoulQuestion
func (t *Question) MergeNoulQuestion(v NoulQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"noul"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChoiceQuestion returns the union data inside the Question as a ChoiceQuestion
func (t Question) AsChoiceQuestion() (ChoiceQuestion, error) {
	var body ChoiceQuestion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceQuestion overwrites any union data inside the Question as the provided ChoiceQuestion
func (t *Question) FromChoiceQuestion(v ChoiceQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"choice"}`))
	t.union = b
	return err
}

// MergeChoiceQuestion performs a merge with any union data inside the Question, using the provided ChoiceQuestion
func (t *Question) MergeChoiceQuestion(v ChoiceQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"choice"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreQuestion returns the union data inside the Question as a ScoreQuestion
func (t Question) AsScoreQuestion() (ScoreQuestion, error) {
	var body ScoreQuestion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreQuestion overwrites any union data inside the Question as the provided ScoreQuestion
func (t *Question) FromScoreQuestion(v ScoreQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"score"}`))
	t.union = b
	return err
}

// MergeScoreQuestion performs a merge with any union data inside the Question, using the provided ScoreQuestion
func (t *Question) MergeScoreQuestion(v ScoreQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"score"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Question) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Question) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "choice":
		return t.AsChoiceQuestion()
	case "noul":
		return t.AsNoulQuestion()
	case "score":
		return t.AsScoreQuestion()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Question) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Question) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsScoreAnswerLegend0 returns the union data inside the ScoreAnswer_Legend_AdditionalProperties as a ScoreAnswerLegend0
func (t ScoreAnswer_Legend_AdditionalProperties) AsScoreAnswerLegend0() (ScoreAnswerLegend0, error) {
	var body ScoreAnswerLegend0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreAnswerLegend0 overwrites any union data inside the ScoreAnswer_Legend_AdditionalProperties as the provided ScoreAnswerLegend0
func (t *ScoreAnswer_Legend_AdditionalProperties) FromScoreAnswerLegend0(v ScoreAnswerLegend0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreAnswerLegend0 performs a merge with any union data inside the ScoreAnswer_Legend_AdditionalProperties, using the provided ScoreAnswerLegend0
func (t *ScoreAnswer_Legend_AdditionalProperties) MergeScoreAnswerLegend0(v ScoreAnswerLegend0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreAnswerLegend1 returns the union data inside the ScoreAnswer_Legend_AdditionalProperties as a ScoreAnswerLegend1
func (t ScoreAnswer_Legend_AdditionalProperties) AsScoreAnswerLegend1() (ScoreAnswerLegend1, error) {
	var body ScoreAnswerLegend1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreAnswerLegend1 overwrites any union data inside the ScoreAnswer_Legend_AdditionalProperties as the provided ScoreAnswerLegend1
func (t *ScoreAnswer_Legend_AdditionalProperties) FromScoreAnswerLegend1(v ScoreAnswerLegend1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreAnswerLegend1 performs a merge with any union data inside the ScoreAnswer_Legend_AdditionalProperties, using the provided ScoreAnswerLegend1
func (t *ScoreAnswer_Legend_AdditionalProperties) MergeScoreAnswerLegend1(v ScoreAnswerLegend1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreAnswerLegend2 returns the union data inside the ScoreAnswer_Legend_AdditionalProperties as a ScoreAnswerLegend2
func (t ScoreAnswer_Legend_AdditionalProperties) AsScoreAnswerLegend2() (ScoreAnswerLegend2, error) {
	var body ScoreAnswerLegend2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreAnswerLegend2 overwrites any union data inside the ScoreAnswer_Legend_AdditionalProperties as the provided ScoreAnswerLegend2
func (t *ScoreAnswer_Legend_AdditionalProperties) FromScoreAnswerLegend2(v ScoreAnswerLegend2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreAnswerLegend2 performs a merge with any union data inside the ScoreAnswer_Legend_AdditionalProperties, using the provided ScoreAnswerLegend2
func (t *ScoreAnswer_Legend_AdditionalProperties) MergeScoreAnswerLegend2(v ScoreAnswerLegend2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ScoreAnswer_Legend_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ScoreAnswer_Legend_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsScoreQuestionCriteria0 returns the union data inside the ScoreQuestion_Criteria_Item as a ScoreQuestionCriteria0
func (t ScoreQuestion_Criteria_Item) AsScoreQuestionCriteria0() (ScoreQuestionCriteria0, error) {
	var body ScoreQuestionCriteria0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreQuestionCriteria0 overwrites any union data inside the ScoreQuestion_Criteria_Item as the provided ScoreQuestionCriteria0
func (t *ScoreQuestion_Criteria_Item) FromScoreQuestionCriteria0(v ScoreQuestionCriteria0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreQuestionCriteria0 performs a merge with any union data inside the ScoreQuestion_Criteria_Item, using the provided ScoreQuestionCriteria0
func (t *ScoreQuestion_Criteria_Item) MergeScoreQuestionCriteria0(v ScoreQuestionCriteria0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreQuestionCriteria1 returns the union data inside the ScoreQuestion_Criteria_Item as a ScoreQuestionCriteria1
func (t ScoreQuestion_Criteria_Item) AsScoreQuestionCriteria1() (ScoreQuestionCriteria1, error) {
	var body ScoreQuestionCriteria1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreQuestionCriteria1 overwrites any union data inside the ScoreQuestion_Criteria_Item as the provided ScoreQuestionCriteria1
func (t *ScoreQuestion_Criteria_Item) FromScoreQuestionCriteria1(v ScoreQuestionCriteria1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreQuestionCriteria1 performs a merge with any union data inside the ScoreQuestion_Criteria_Item, using the provided ScoreQuestionCriteria1
func (t *ScoreQuestion_Criteria_Item) MergeScoreQuestionCriteria1(v ScoreQuestionCriteria1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreQuestionCriteria2 returns the union data inside the ScoreQuestion_Criteria_Item as a ScoreQuestionCriteria2
func (t ScoreQuestion_Criteria_Item) AsScoreQuestionCriteria2() (ScoreQuestionCriteria2, error) {
	var body ScoreQuestionCriteria2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreQuestionCriteria2 overwrites any union data inside the ScoreQuestion_Criteria_Item as the provided ScoreQuestionCriteria2
func (t *ScoreQuestion_Criteria_Item) FromScoreQuestionCriteria2(v ScoreQuestionCriteria2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreQuestionCriteria2 performs a merge with any union data inside the ScoreQuestion_Criteria_Item, using the provided ScoreQuestionCriteria2
func (t *ScoreQuestion_Criteria_Item) MergeScoreQuestionCriteria2(v ScoreQuestionCriteria2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ScoreQuestion_Criteria_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ScoreQuestion_Criteria_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsScoreQuestionInstructions0 returns the union data inside the ScoreQuestion_Instructions as a ScoreQuestionInstructions0
func (t ScoreQuestion_Instructions) AsScoreQuestionInstructions0() (ScoreQuestionInstructions0, error) {
	var body ScoreQuestionInstructions0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreQuestionInstructions0 overwrites any union data inside the ScoreQuestion_Instructions as the provided ScoreQuestionInstructions0
func (t *ScoreQuestion_Instructions) FromScoreQuestionInstructions0(v ScoreQuestionInstructions0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreQuestionInstructions0 performs a merge with any union data inside the ScoreQuestion_Instructions, using the provided ScoreQuestionInstructions0
func (t *ScoreQuestion_Instructions) MergeScoreQuestionInstructions0(v ScoreQuestionInstructions0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreQuestionInstructions1 returns the union data inside the ScoreQuestion_Instructions as a ScoreQuestionInstructions1
func (t ScoreQuestion_Instructions) AsScoreQuestionInstructions1() (ScoreQuestionInstructions1, error) {
	var body ScoreQuestionInstructions1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreQuestionInstructions1 overwrites any union data inside the ScoreQuestion_Instructions as the provided ScoreQuestionInstructions1
func (t *ScoreQuestion_Instructions) FromScoreQuestionInstructions1(v ScoreQuestionInstructions1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreQuestionInstructions1 performs a merge with any union data inside the ScoreQuestion_Instructions, using the provided ScoreQuestionInstructions1
func (t *ScoreQuestion_Instructions) MergeScoreQuestionInstructions1(v ScoreQuestionInstructions1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreQuestionInstructions2 returns the union data inside the ScoreQuestion_Instructions as a ScoreQuestionInstructions2
func (t ScoreQuestion_Instructions) AsScoreQuestionInstructions2() (ScoreQuestionInstructions2, error) {
	var body ScoreQuestionInstructions2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreQuestionInstructions2 overwrites any union data inside the ScoreQuestion_Instructions as the provided ScoreQuestionInstructions2
func (t *ScoreQuestion_Instructions) FromScoreQuestionInstructions2(v ScoreQuestionInstructions2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScoreQuestionInstructions2 performs a merge with any union data inside the ScoreQuestion_Instructions, using the provided ScoreQuestionInstructions2
func (t *ScoreQuestion_Instructions) MergeScoreQuestionInstructions2(v ScoreQuestionInstructions2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ScoreQuestion_Instructions) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ScoreQuestion_Instructions) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSystemOneRequestState0 returns the union data inside the SystemOneRequest_State as a SystemOneRequestState0
func (t SystemOneRequest_State) AsSystemOneRequestState0() (SystemOneRequestState0, error) {
	var body SystemOneRequestState0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemOneRequestState0 overwrites any union data inside the SystemOneRequest_State as the provided SystemOneRequestState0
func (t *SystemOneRequest_State) FromSystemOneRequestState0(v SystemOneRequestState0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemOneRequestState0 performs a merge with any union data inside the SystemOneRequest_State, using the provided SystemOneRequestState0
func (t *SystemOneRequest_State) MergeSystemOneRequestState0(v SystemOneRequestState0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemOneRequestState1 returns the union data inside the SystemOneRequest_State as a SystemOneRequestState1
func (t SystemOneRequest_State) AsSystemOneRequestState1() (SystemOneRequestState1, error) {
	var body SystemOneRequestState1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemOneRequestState1 overwrites any union data inside the SystemOneRequest_State as the provided SystemOneRequestState1
func (t *SystemOneRequest_State) FromSystemOneRequestState1(v SystemOneRequestState1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemOneRequestState1 performs a merge with any union data inside the SystemOneRequest_State, using the provided SystemOneRequestState1
func (t *SystemOneRequest_State) MergeSystemOneRequestState1(v SystemOneRequestState1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemOneRequestState2 returns the union data inside the SystemOneRequest_State as a SystemOneRequestState2
func (t SystemOneRequest_State) AsSystemOneRequestState2() (SystemOneRequestState2, error) {
	var body SystemOneRequestState2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemOneRequestState2 overwrites any union data inside the SystemOneRequest_State as the provided SystemOneRequestState2
func (t *SystemOneRequest_State) FromSystemOneRequestState2(v SystemOneRequestState2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemOneRequestState2 performs a merge with any union data inside the SystemOneRequest_State, using the provided SystemOneRequestState2
func (t *SystemOneRequest_State) MergeSystemOneRequestState2(v SystemOneRequestState2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SystemOneRequest_State) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SystemOneRequest_State) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// GeneratedClient which conforms to the OpenAPI3 specification for this service.
type GeneratedClient struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*GeneratedClient) error

// Creates a new GeneratedClient, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*GeneratedClient, error) {
	// create a client with sane default values
	client := GeneratedClient{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *GeneratedClient) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *GeneratedClient) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ModelsV1V1ModelsGet Models V1
	//
	// List the models and aliases available to the authenticated account.
	//
	// Pass a returned model name as `model` in a POST /v1/systemone request.
	//
	// Corresponds with GET /v1/models (the `ModelsV1V1ModelsGet` operationId).
	ModelsV1V1ModelsGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SystemoneV1SystemonePostWithBody Systemone
	//
	// Answer one or more questions about the content supplied in `state`.
	//
	// You can mix question types in one request. Answers use the same names as the
	// questions, so you can match each result to its question. The response also includes
	// the model used and token usage.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/systemone (the `SystemoneV1SystemonePost` operationId).
	SystemoneV1SystemonePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SystemoneV1SystemonePost Systemone
	//
	// Answer one or more questions about the content supplied in `state`.
	//
	// You can mix question types in one request. Answers use the same names as the
	// questions, so you can match each result to its question. The response also includes
	// the model used and token usage.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/systemone (the `SystemoneV1SystemonePost` operationId).
	SystemoneV1SystemonePost(ctx context.Context, body SystemoneV1SystemonePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ModelsV1V1ModelsGet Models V1
//
// List the models and aliases available to the authenticated account.
//
// Pass a returned model name as `model` in a POST /v1/systemone request.
//
// Corresponds with GET /v1/models (the `ModelsV1V1ModelsGet` operationId).
func (c *GeneratedClient) ModelsV1V1ModelsGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewModelsV1V1ModelsGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SystemoneV1SystemonePostWithBody Systemone
//
// Answer one or more questions about the content supplied in `state`.
//
// You can mix question types in one request. Answers use the same names as the
// questions, so you can match each result to its question. The response also includes
// the model used and token usage.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/systemone (the `SystemoneV1SystemonePost` operationId).
func (c *GeneratedClient) SystemoneV1SystemonePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSystemoneV1SystemonePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SystemoneV1SystemonePost Systemone
//
// Answer one or more questions about the content supplied in `state`.
//
// You can mix question types in one request. Answers use the same names as the
// questions, so you can match each result to its question. The response also includes
// the model used and token usage.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/systemone (the `SystemoneV1SystemonePost` operationId).
func (c *GeneratedClient) SystemoneV1SystemonePost(ctx context.Context, body SystemoneV1SystemonePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSystemoneV1SystemonePostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewModelsV1V1ModelsGetRequest constructs an http.Request for the ModelsV1V1ModelsGet method
func NewModelsV1V1ModelsGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSystemoneV1SystemonePostRequest calls the generic SystemoneV1SystemonePost builder with application/json body
func NewSystemoneV1SystemonePostRequest(server string, body SystemoneV1SystemonePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSystemoneV1SystemonePostRequestWithBody(server, "application/json", bodyReader)
}

// NewSystemoneV1SystemonePostRequestWithBody constructs an http.Request for the SystemoneV1SystemonePost method, with any body, and a specified content type
func NewSystemoneV1SystemonePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/systemone")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *GeneratedClient) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *GeneratedClient) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ModelsV1V1ModelsGetWithResponse Models V1
	//
	// List the models and aliases available to the authenticated account.
	//
	// Pass a returned model name as `model` in a POST /v1/systemone request.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/models (the `ModelsV1V1ModelsGet` operationId).
	ModelsV1V1ModelsGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ModelsV1V1ModelsGetResponse, error)

	// SystemoneV1SystemonePostWithBodyWithResponse Systemone
	//
	// Answer one or more questions about the content supplied in `state`.
	//
	// You can mix question types in one request. Answers use the same names as the
	// questions, so you can match each result to its question. The response also includes
	// the model used and token usage.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/systemone (the `SystemoneV1SystemonePost` operationId).
	SystemoneV1SystemonePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SystemoneV1SystemonePostResponse, error)

	// SystemoneV1SystemonePostWithResponse Systemone
	//
	// Answer one or more questions about the content supplied in `state`.
	//
	// You can mix question types in one request. Answers use the same names as the
	// questions, so you can match each result to its question. The response also includes
	// the model used and token usage.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/systemone (the `SystemoneV1SystemonePost` operationId).
	SystemoneV1SystemonePostWithResponse(ctx context.Context, body SystemoneV1SystemonePostJSONRequestBody, reqEditors ...RequestEditorFn) (*SystemoneV1SystemonePostResponse, error)
}

type ModelsV1V1ModelsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ModelMetadataList
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *HTTPValidationError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ModelsV1V1ModelsGetResponse) GetJSON200() *ModelMetadataList {
	return r.JSON200
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r ModelsV1V1ModelsGetResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r ModelsV1V1ModelsGetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ModelsV1V1ModelsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ModelsV1V1ModelsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ModelsV1V1ModelsGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SystemoneV1SystemonePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SystemOneResponse
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *HTTPValidationError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SystemoneV1SystemonePostResponse) GetJSON200() *SystemOneResponse {
	return r.JSON200
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r SystemoneV1SystemonePostResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r SystemoneV1SystemonePostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SystemoneV1SystemonePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SystemoneV1SystemonePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SystemoneV1SystemonePostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ModelsV1V1ModelsGetWithResponse Models V1
//
// List the models and aliases available to the authenticated account.
//
// Pass a returned model name as `model` in a POST /v1/systemone request.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/models (the `ModelsV1V1ModelsGet` operationId).
func (c *ClientWithResponses) ModelsV1V1ModelsGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ModelsV1V1ModelsGetResponse, error) {
	rsp, err := c.ModelsV1V1ModelsGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseModelsV1V1ModelsGetResponse(rsp)
}

// SystemoneV1SystemonePostWithBodyWithResponse Systemone
//
// Answer one or more questions about the content supplied in `state`.
//
// You can mix question types in one request. Answers use the same names as the
// questions, so you can match each result to its question. The response also includes
// the model used and token usage.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/systemone (the `SystemoneV1SystemonePost` operationId).
func (c *ClientWithResponses) SystemoneV1SystemonePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SystemoneV1SystemonePostResponse, error) {
	rsp, err := c.SystemoneV1SystemonePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSystemoneV1SystemonePostResponse(rsp)
}

// SystemoneV1SystemonePostWithResponse Systemone
//
// Answer one or more questions about the content supplied in `state`.
//
// You can mix question types in one request. Answers use the same names as the
// questions, so you can match each result to its question. The response also includes
// the model used and token usage.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/systemone (the `SystemoneV1SystemonePost` operationId).
func (c *ClientWithResponses) SystemoneV1SystemonePostWithResponse(ctx context.Context, body SystemoneV1SystemonePostJSONRequestBody, reqEditors ...RequestEditorFn) (*SystemoneV1SystemonePostResponse, error) {
	rsp, err := c.SystemoneV1SystemonePost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSystemoneV1SystemonePostResponse(rsp)
}

// ParseModelsV1V1ModelsGetResponse parses an HTTP response from a ModelsV1V1ModelsGetWithResponse call
func ParseModelsV1V1ModelsGetResponse(rsp *http.Response) (*ModelsV1V1ModelsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ModelsV1V1ModelsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelMetadataList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseSystemoneV1SystemonePostResponse parses an HTTP response from a SystemoneV1SystemonePostWithResponse call
func ParseSystemoneV1SystemonePostResponse(rsp *http.Response) (*SystemoneV1SystemonePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SystemoneV1SystemonePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SystemOneResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
