// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/vibecheck/internal/pkg/db/models"
)

func newEvaluation(db *gorm.DB, opts ...gen.DOOption) evaluation {
	_evaluation := evaluation{}

	_evaluation.evaluationDo.UseDB(db, opts...)
	_evaluation.evaluationDo.UseModel(&models.Evaluation{})

	tableName := _evaluation.evaluationDo.TableName()
	_evaluation.ALL = field.NewAsterisk(tableName)
	_evaluation.ID = field.NewField(tableName, "id")
	_evaluation.PolicySnapshotHash = field.NewString(tableName, "policy_snapshot_hash")
	_evaluation.PolicyName = field.NewString(tableName, "policy_name")
	_evaluation.PolicyVersion = field.NewString(tableName, "policy_version")
	_evaluation.PolicyKind = field.NewString(tableName, "policy_kind")
	_evaluation.Status = field.NewString(tableName, "status")
	_evaluation.Outcome = field.NewString(tableName, "outcome")
	_evaluation.MatchedRuleID = field.NewString(tableName, "matched_rule_id")
	_evaluation.ExecutionPath = field.NewString(tableName, "execution_path")
	_evaluation.RequestedModel = field.NewString(tableName, "requested_model")
	_evaluation.ResolvedModel = field.NewString(tableName, "resolved_model")
	_evaluation.AnswersJSON = field.NewString(tableName, "answers_json")
	_evaluation.InputTokens = field.NewInt(tableName, "input_tokens")
	_evaluation.OutputTokens = field.NewInt(tableName, "output_tokens")
	_evaluation.ProviderAttempts = field.NewInt(tableName, "provider_attempts")
	_evaluation.ProviderDurationMS = field.NewInt64(tableName, "provider_duration_ms")
	_evaluation.TotalDurationMS = field.NewInt64(tableName, "total_duration_ms")
	_evaluation.RequestID = field.NewString(tableName, "request_id")
	_evaluation.MetadataJSON = field.NewString(tableName, "metadata_json")
	_evaluation.EncryptedInput = field.NewBytes(tableName, "encrypted_input")
	_evaluation.FailureCode = field.NewString(tableName, "failure_code")
	_evaluation.CreatedAt = field.NewTime(tableName, "created_at")

	_evaluation.fillFieldMap()

	return _evaluation
}

type evaluation struct {
	evaluationDo

	ALL                field.Asterisk
	ID                 field.Field
	PolicySnapshotHash field.String
	PolicyName         field.String
	PolicyVersion      field.String
	PolicyKind         field.String
	Status             field.String
	Outcome            field.String
	MatchedRuleID      field.String
	ExecutionPath      field.String
	RequestedModel     field.String
	ResolvedModel      field.String
	AnswersJSON        field.String
	InputTokens        field.Int
	OutputTokens       field.Int
	ProviderAttempts   field.Int
	ProviderDurationMS field.Int64
	TotalDurationMS    field.Int64
	RequestID          field.String
	MetadataJSON       field.String
	EncryptedInput     field.Bytes
	FailureCode        field.String
	CreatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (e evaluation) Table(newTableName string) *evaluation {
	e.evaluationDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e evaluation) As(alias string) *evaluation {
	e.evaluationDo.DO = *(e.evaluationDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *evaluation) updateTableName(table string) *evaluation {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewField(table, "id")
	e.PolicySnapshotHash = field.NewString(table, "policy_snapshot_hash")
	e.PolicyName = field.NewString(table, "policy_name")
	e.PolicyVersion = field.NewString(table, "policy_version")
	e.PolicyKind = field.NewString(table, "policy_kind")
	e.Status = field.NewString(table, "status")
	e.Outcome = field.NewString(table, "outcome")
	e.MatchedRuleID = field.NewString(table, "matched_rule_id")
	e.ExecutionPath = field.NewString(table, "execution_path")
	e.RequestedModel = field.NewString(table, "requested_model")
	e.ResolvedModel = field.NewString(table, "resolved_model")
	e.AnswersJSON = field.NewString(table, "answers_json")
	e.InputTokens = field.NewInt(table, "input_tokens")
	e.OutputTokens = field.NewInt(table, "output_tokens")
	e.ProviderAttempts = field.NewInt(table, "provider_attempts")
	e.ProviderDurationMS = field.NewInt64(table, "provider_duration_ms")
	e.TotalDurationMS = field.NewInt64(table, "total_duration_ms")
	e.RequestID = field.NewString(table, "request_id")
	e.MetadataJSON = field.NewString(table, "metadata_json")
	e.EncryptedInput = field.NewBytes(table, "encrypted_input")
	e.FailureCode = field.NewString(table, "failure_code")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *evaluation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *evaluation) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 22)
	e.fieldMap["id"] = e.ID
	e.fieldMap["policy_snapshot_hash"] = e.PolicySnapshotHash
	e.fieldMap["policy_name"] = e.PolicyName
	e.fieldMap["policy_version"] = e.PolicyVersion
	e.fieldMap["policy_kind"] = e.PolicyKind
	e.fieldMap["status"] = e.Status
	e.fieldMap["outcome"] = e.Outcome
	e.fieldMap["matched_rule_id"] = e.MatchedRuleID
	e.fieldMap["execution_path"] = e.ExecutionPath
	e.fieldMap["requested_model"] = e.RequestedModel
	e.fieldMap["resolved_model"] = e.ResolvedModel
	e.fieldMap["answers_json"] = e.AnswersJSON
	e.fieldMap["input_tokens"] = e.InputTokens
	e.fieldMap["output_tokens"] = e.OutputTokens
	e.fieldMap["provider_attempts"] = e.ProviderAttempts
	e.fieldMap["provider_duration_ms"] = e.ProviderDurationMS
	e.fieldMap["total_duration_ms"] = e.TotalDurationMS
	e.fieldMap["request_id"] = e.RequestID
	e.fieldMap["metadata_json"] = e.MetadataJSON
	e.fieldMap["encrypted_input"] = e.EncryptedInput
	e.fieldMap["failure_code"] = e.FailureCode
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e evaluation) clone(db *gorm.DB) evaluation {
	e.evaluationDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e evaluation) replaceDB(db *gorm.DB) evaluation {
	e.evaluationDo.ReplaceDB(db)
	return e
}

type evaluationDo struct{ gen.DO }

type IEvaluationDo interface {
	gen.SubQuery
	Debug() IEvaluationDo
	WithContext(ctx context.Context) IEvaluationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEvaluationDo
	WriteDB() IEvaluationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEvaluationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEvaluationDo
	Not(conds ...gen.Condition) IEvaluationDo
	Or(conds ...gen.Condition) IEvaluationDo
	Select(conds ...field.Expr) IEvaluationDo
	Where(conds ...gen.Condition) IEvaluationDo
	Order(conds ...field.Expr) IEvaluationDo
	Distinct(cols ...field.Expr) IEvaluationDo
	Omit(cols ...field.Expr) IEvaluationDo
	Join(table schema.Tabler, on ...field.Expr) IEvaluationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEvaluationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEvaluationDo
	Group(cols ...field.Expr) IEvaluationDo
	Having(conds ...gen.Condition) IEvaluationDo
	Limit(limit int) IEvaluationDo
	Offset(offset int) IEvaluationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEvaluationDo
	Unscoped() IEvaluationDo
	Create(values ...*models.Evaluation) error
	CreateInBatches(values []*models.Evaluation, batchSize int) error
	Save(values ...*models.Evaluation) error
	First() (*models.Evaluation, error)
	Take() (*models.Evaluation, error)
	Last() (*models.Evaluation, error)
	Find() ([]*models.Evaluation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Evaluation, err error)
	FindInBatches(result *[]*models.Evaluation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Evaluation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEvaluationDo
	Assign(attrs ...field.AssignExpr) IEvaluationDo
	Joins(fields ...field.RelationField) IEvaluationDo
	Preload(fields ...field.RelationField) IEvaluationDo
	FirstOrInit() (*models.Evaluation, error)
	FirstOrCreate() (*models.Evaluation, error)
	FindByPage(offset int, limit int) (result []*models.Evaluation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEvaluationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e evaluationDo) Debug() IEvaluationDo {
	return e.withDO(e.DO.Debug())
}

func (e evaluationDo) WithContext(ctx context.Context) IEvaluationDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e evaluationDo) ReadDB() IEvaluationDo {
	return e.Clauses(dbresolver.Read)
}

func (e evaluationDo) WriteDB() IEvaluationDo {
	return e.Clauses(dbresolver.Write)
}

func (e evaluationDo) Session(config *gorm.Session) IEvaluationDo {
	return e.withDO(e.DO.Session(config))
}

func (e evaluationDo) Clauses(conds ...clause.Expression) IEvaluationDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e evaluationDo) Returning(value interface{}, columns ...string) IEvaluationDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e evaluationDo) Not(conds ...gen.Condition) IEvaluationDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e evaluationDo) Or(conds ...gen.Condition) IEvaluationDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e evaluationDo) Select(conds ...field.Expr) IEvaluationDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e evaluationDo) Where(conds ...gen.Condition) IEvaluationDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e evaluationDo) Order(conds ...field.Expr) IEvaluationDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e evaluationDo) Distinct(cols ...field.Expr) IEvaluationDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e evaluationDo) Omit(cols ...field.Expr) IEvaluationDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e evaluationDo) Join(table schema.Tabler, on ...field.Expr) IEvaluationDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e evaluationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEvaluationDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e evaluationDo) RightJoin(table schema.Tabler, on ...field.Expr) IEvaluationDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e evaluationDo) Group(cols ...field.Expr) IEvaluationDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e evaluationDo) Having(conds ...gen.Condition) IEvaluationDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e evaluationDo) Limit(limit int) IEvaluationDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e evaluationDo) Offset(offset int) IEvaluationDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e evaluationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEvaluationDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e evaluationDo) Unscoped() IEvaluationDo {
	return e.withDO(e.DO.Unscoped())
}

func (e evaluationDo) Create(values ...*models.Evaluation) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e evaluationDo) CreateInBatches(values []*models.Evaluation, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e evaluationDo) Save(values ...*models.Evaluation) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e evaluationDo) First() (*models.Evaluation, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Evaluation), nil
	}
}

func (e evaluationDo) Take() (*models.Evaluation, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Evaluation), nil
	}
}

func (e evaluationDo) Last() (*models.Evaluation, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Evaluation), nil
	}
}

func (e evaluationDo) Find() ([]*models.Evaluation, error) {
	result, err := e.DO.Find()
	return result.([]*models.Evaluation), err
}

func (e evaluationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Evaluation, err error) {
	buf := make([]*models.Evaluation, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e evaluationDo) FindInBatches(result *[]*models.Evaluation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e evaluationDo) Attrs(attrs ...field.AssignExpr) IEvaluationDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e evaluationDo) Assign(attrs ...field.AssignExpr) IEvaluationDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e evaluationDo) Joins(fields ...field.RelationField) IEvaluationDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e evaluationDo) Preload(fields ...field.RelationField) IEvaluationDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e evaluationDo) FirstOrInit() (*models.Evaluation, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Evaluation), nil
	}
}

func (e evaluationDo) FirstOrCreate() (*models.Evaluation, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Evaluation), nil
	}
}

func (e evaluationDo) FindByPage(offset int, limit int) (result []*models.Evaluation, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e evaluationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e evaluationDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e evaluationDo) Delete(models ...*models.Evaluation) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *evaluationDo) withDO(do gen.Dao) *evaluationDo {
	e.DO = *do.(*gen.DO)
	return e
}
