// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/vibecheck/internal/pkg/db/models"
)

func newIdempotencyRecord(db *gorm.DB, opts ...gen.DOOption) idempotencyRecord {
	_idempotencyRecord := idempotencyRecord{}

	_idempotencyRecord.idempotencyRecordDo.UseDB(db, opts...)
	_idempotencyRecord.idempotencyRecordDo.UseModel(&models.IdempotencyRecord{})

	tableName := _idempotencyRecord.idempotencyRecordDo.TableName()
	_idempotencyRecord.ALL = field.NewAsterisk(tableName)
	_idempotencyRecord.KeyHash = field.NewString(tableName, "key_hash")
	_idempotencyRecord.CanonicalRequestHash = field.NewString(tableName, "canonical_request_hash")
	_idempotencyRecord.EvaluationID = field.NewField(tableName, "evaluation_id")
	_idempotencyRecord.ExpiresAt = field.NewTime(tableName, "expires_at")
	_idempotencyRecord.CreatedAt = field.NewTime(tableName, "created_at")

	_idempotencyRecord.fillFieldMap()

	return _idempotencyRecord
}

type idempotencyRecord struct {
	idempotencyRecordDo

	ALL                  field.Asterisk
	KeyHash              field.String
	CanonicalRequestHash field.String
	EvaluationID         field.Field
	ExpiresAt            field.Time
	CreatedAt            field.Time

	fieldMap map[string]field.Expr
}

func (i idempotencyRecord) Table(newTableName string) *idempotencyRecord {
	i.idempotencyRecordDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i idempotencyRecord) As(alias string) *idempotencyRecord {
	i.idempotencyRecordDo.DO = *(i.idempotencyRecordDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *idempotencyRecord) updateTableName(table string) *idempotencyRecord {
	i.ALL = field.NewAsterisk(table)
	i.KeyHash = field.NewString(table, "key_hash")
	i.CanonicalRequestHash = field.NewString(table, "canonical_request_hash")
	i.EvaluationID = field.NewField(table, "evaluation_id")
	i.ExpiresAt = field.NewTime(table, "expires_at")
	i.CreatedAt = field.NewTime(table, "created_at")

	i.fillFieldMap()

	return i
}

func (i *idempotencyRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *idempotencyRecord) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 5)
	i.fieldMap["key_hash"] = i.KeyHash
	i.fieldMap["canonical_request_hash"] = i.CanonicalRequestHash
	i.fieldMap["evaluation_id"] = i.EvaluationID
	i.fieldMap["expires_at"] = i.ExpiresAt
	i.fieldMap["created_at"] = i.CreatedAt
}

func (i idempotencyRecord) clone(db *gorm.DB) idempotencyRecord {
	i.idempotencyRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i idempotencyRecord) replaceDB(db *gorm.DB) idempotencyRecord {
	i.idempotencyRecordDo.ReplaceDB(db)
	return i
}

type idempotencyRecordDo struct{ gen.DO }

type IIdempotencyRecordDo interface {
	gen.SubQuery
	Debug() IIdempotencyRecordDo
	WithContext(ctx context.Context) IIdempotencyRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIdempotencyRecordDo
	WriteDB() IIdempotencyRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIdempotencyRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIdempotencyRecordDo
	Not(conds ...gen.Condition) IIdempotencyRecordDo
	Or(conds ...gen.Condition) IIdempotencyRecordDo
	Select(conds ...field.Expr) IIdempotencyRecordDo
	Where(conds ...gen.Condition) IIdempotencyRecordDo
	Order(conds ...field.Expr) IIdempotencyRecordDo
	Distinct(cols ...field.Expr) IIdempotencyRecordDo
	Omit(cols ...field.Expr) IIdempotencyRecordDo
	Join(table schema.Tabler, on ...field.Expr) IIdempotencyRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIdempotencyRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIdempotencyRecordDo
	Group(cols ...field.Expr) IIdempotencyRecordDo
	Having(conds ...gen.Condition) IIdempotencyRecordDo
	Limit(limit int) IIdempotencyRecordDo
	Offset(offset int) IIdempotencyRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIdempotencyRecordDo
	Unscoped() IIdempotencyRecordDo
	Create(values ...*models.IdempotencyRecord) error
	CreateInBatches(values []*models.IdempotencyRecord, batchSize int) error
	Save(values ...*models.IdempotencyRecord) error
	First() (*models.IdempotencyRecord, error)
	Take() (*models.IdempotencyRecord, error)
	Last() (*models.IdempotencyRecord, error)
	Find() ([]*models.IdempotencyRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.IdempotencyRecord, err error)
	FindInBatches(result *[]*models.IdempotencyRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.IdempotencyRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIdempotencyRecordDo
	Assign(attrs ...field.AssignExpr) IIdempotencyRecordDo
	Joins(fields ...field.RelationField) IIdempotencyRecordDo
	Preload(fields ...field.RelationField) IIdempotencyRecordDo
	FirstOrInit() (*models.IdempotencyRecord, error)
	FirstOrCreate() (*models.IdempotencyRecord, error)
	FindByPage(offset int, limit int) (result []*models.IdempotencyRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIdempotencyRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i idempotencyRecordDo) Debug() IIdempotencyRecordDo {
	return i.withDO(i.DO.Debug())
}

func (i idempotencyRecordDo) WithContext(ctx context.Context) IIdempotencyRecordDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i idempotencyRecordDo) ReadDB() IIdempotencyRecordDo {
	return i.Clauses(dbresolver.Read)
}

func (i idempotencyRecordDo) WriteDB() IIdempotencyRecordDo {
	return i.Clauses(dbresolver.Write)
}

func (i idempotencyRecordDo) Session(config *gorm.Session) IIdempotencyRecordDo {
	return i.withDO(i.DO.Session(config))
}

func (i idempotencyRecordDo) Clauses(conds ...clause.Expression) IIdempotencyRecordDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i idempotencyRecordDo) Returning(value interface{}, columns ...string) IIdempotencyRecordDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i idempotencyRecordDo) Not(conds ...gen.Condition) IIdempotencyRecordDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i idempotencyRecordDo) Or(conds ...gen.Condition) IIdempotencyRecordDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i idempotencyRecordDo) Select(conds ...field.Expr) IIdempotencyRecordDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i idempotencyRecordDo) Where(conds ...gen.Condition) IIdempotencyRecordDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i idempotencyRecordDo) Order(conds ...field.Expr) IIdempotencyRecordDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i idempotencyRecordDo) Distinct(cols ...field.Expr) IIdempotencyRecordDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i idempotencyRecordDo) Omit(cols ...field.Expr) IIdempotencyRecordDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i idempotencyRecordDo) Join(table schema.Tabler, on ...field.Expr) IIdempotencyRecordDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i idempotencyRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIdempotencyRecordDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i idempotencyRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IIdempotencyRecordDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i idempotencyRecordDo) Group(cols ...field.Expr) IIdempotencyRecordDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i idempotencyRecordDo) Having(conds ...gen.Condition) IIdempotencyRecordDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i idempotencyRecordDo) Limit(limit int) IIdempotencyRecordDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i idempotencyRecordDo) Offset(offset int) IIdempotencyRecordDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i idempotencyRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIdempotencyRecordDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i idempotencyRecordDo) Unscoped() IIdempotencyRecordDo {
	return i.withDO(i.DO.Unscoped())
}

func (i idempotencyRecordDo) Create(values ...*models.IdempotencyRecord) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i idempotencyRecordDo) CreateInBatches(values []*models.IdempotencyRecord, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i idempotencyRecordDo) Save(values ...*models.IdempotencyRecord) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i idempotencyRecordDo) First() (*models.IdempotencyRecord, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdempotencyRecord), nil
	}
}

func (i idempotencyRecordDo) Take() (*models.IdempotencyRecord, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdempotencyRecord), nil
	}
}

func (i idempotencyRecordDo) Last() (*models.IdempotencyRecord, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdempotencyRecord), nil
	}
}

func (i idempotencyRecordDo) Find() ([]*models.IdempotencyRecord, error) {
	result, err := i.DO.Find()
	return result.([]*models.IdempotencyRecord), err
}

func (i idempotencyRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.IdempotencyRecord, err error) {
	buf := make([]*models.IdempotencyRecord, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i idempotencyRecordDo) FindInBatches(result *[]*models.IdempotencyRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i idempotencyRecordDo) Attrs(attrs ...field.AssignExpr) IIdempotencyRecordDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i idempotencyRecordDo) Assign(attrs ...field.AssignExpr) IIdempotencyRecordDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i idempotencyRecordDo) Joins(fields ...field.RelationField) IIdempotencyRecordDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i idempotencyRecordDo) Preload(fields ...field.RelationField) IIdempotencyRecordDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i idempotencyRecordDo) FirstOrInit() (*models.IdempotencyRecord, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdempotencyRecord), nil
	}
}

func (i idempotencyRecordDo) FirstOrCreate() (*models.IdempotencyRecord, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdempotencyRecord), nil
	}
}

func (i idempotencyRecordDo) FindByPage(offset int, limit int) (result []*models.IdempotencyRecord, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i idempotencyRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i idempotencyRecordDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i idempotencyRecordDo) Delete(models ...*models.IdempotencyRecord) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *idempotencyRecordDo) withDO(do gen.Dao) *idempotencyRecordDo {
	i.DO = *do.(*gen.DO)
	return i
}
