// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/psyb0t/vibecheck/internal/pkg/db/models"
)

func newPolicySnapshot(db *gorm.DB, opts ...gen.DOOption) policySnapshot {
	_policySnapshot := policySnapshot{}

	_policySnapshot.policySnapshotDo.UseDB(db, opts...)
	_policySnapshot.policySnapshotDo.UseModel(&models.PolicySnapshot{})

	tableName := _policySnapshot.policySnapshotDo.TableName()
	_policySnapshot.ALL = field.NewAsterisk(tableName)
	_policySnapshot.Hash = field.NewString(tableName, "hash")
	_policySnapshot.Name = field.NewString(tableName, "name")
	_policySnapshot.Version = field.NewString(tableName, "version")
	_policySnapshot.CanonicalJSON = field.NewString(tableName, "canonical_json")
	_policySnapshot.LoadedAt = field.NewTime(tableName, "loaded_at")

	_policySnapshot.fillFieldMap()

	return _policySnapshot
}

type policySnapshot struct {
	policySnapshotDo

	ALL           field.Asterisk
	Hash          field.String
	Name          field.String
	Version       field.String
	CanonicalJSON field.String
	LoadedAt      field.Time

	fieldMap map[string]field.Expr
}

func (p policySnapshot) Table(newTableName string) *policySnapshot {
	p.policySnapshotDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p policySnapshot) As(alias string) *policySnapshot {
	p.policySnapshotDo.DO = *(p.policySnapshotDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *policySnapshot) updateTableName(table string) *policySnapshot {
	p.ALL = field.NewAsterisk(table)
	p.Hash = field.NewString(table, "hash")
	p.Name = field.NewString(table, "name")
	p.Version = field.NewString(table, "version")
	p.CanonicalJSON = field.NewString(table, "canonical_json")
	p.LoadedAt = field.NewTime(table, "loaded_at")

	p.fillFieldMap()

	return p
}

func (p *policySnapshot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *policySnapshot) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["hash"] = p.Hash
	p.fieldMap["name"] = p.Name
	p.fieldMap["version"] = p.Version
	p.fieldMap["canonical_json"] = p.CanonicalJSON
	p.fieldMap["loaded_at"] = p.LoadedAt
}

func (p policySnapshot) clone(db *gorm.DB) policySnapshot {
	p.policySnapshotDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p policySnapshot) replaceDB(db *gorm.DB) policySnapshot {
	p.policySnapshotDo.ReplaceDB(db)
	return p
}

type policySnapshotDo struct{ gen.DO }

type IPolicySnapshotDo interface {
	gen.SubQuery
	Debug() IPolicySnapshotDo
	WithContext(ctx context.Context) IPolicySnapshotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPolicySnapshotDo
	WriteDB() IPolicySnapshotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPolicySnapshotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPolicySnapshotDo
	Not(conds ...gen.Condition) IPolicySnapshotDo
	Or(conds ...gen.Condition) IPolicySnapshotDo
	Select(conds ...field.Expr) IPolicySnapshotDo
	Where(conds ...gen.Condition) IPolicySnapshotDo
	Order(conds ...field.Expr) IPolicySnapshotDo
	Distinct(cols ...field.Expr) IPolicySnapshotDo
	Omit(cols ...field.Expr) IPolicySnapshotDo
	Join(table schema.Tabler, on ...field.Expr) IPolicySnapshotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPolicySnapshotDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPolicySnapshotDo
	Group(cols ...field.Expr) IPolicySnapshotDo
	Having(conds ...gen.Condition) IPolicySnapshotDo
	Limit(limit int) IPolicySnapshotDo
	Offset(offset int) IPolicySnapshotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicySnapshotDo
	Unscoped() IPolicySnapshotDo
	Create(values ...*models.PolicySnapshot) error
	CreateInBatches(values []*models.PolicySnapshot, batchSize int) error
	Save(values ...*models.PolicySnapshot) error
	First() (*models.PolicySnapshot, error)
	Take() (*models.PolicySnapshot, error)
	Last() (*models.PolicySnapshot, error)
	Find() ([]*models.PolicySnapshot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PolicySnapshot, err error)
	FindInBatches(result *[]*models.PolicySnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.PolicySnapshot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPolicySnapshotDo
	Assign(attrs ...field.AssignExpr) IPolicySnapshotDo
	Joins(fields ...field.RelationField) IPolicySnapshotDo
	Preload(fields ...field.RelationField) IPolicySnapshotDo
	FirstOrInit() (*models.PolicySnapshot, error)
	FirstOrCreate() (*models.PolicySnapshot, error)
	FindByPage(offset int, limit int) (result []*models.PolicySnapshot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPolicySnapshotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p policySnapshotDo) Debug() IPolicySnapshotDo {
	return p.withDO(p.DO.Debug())
}

func (p policySnapshotDo) WithContext(ctx context.Context) IPolicySnapshotDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p policySnapshotDo) ReadDB() IPolicySnapshotDo {
	return p.Clauses(dbresolver.Read)
}

func (p policySnapshotDo) WriteDB() IPolicySnapshotDo {
	return p.Clauses(dbresolver.Write)
}

func (p policySnapshotDo) Session(config *gorm.Session) IPolicySnapshotDo {
	return p.withDO(p.DO.Session(config))
}

func (p policySnapshotDo) Clauses(conds ...clause.Expression) IPolicySnapshotDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p policySnapshotDo) Returning(value interface{}, columns ...string) IPolicySnapshotDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p policySnapshotDo) Not(conds ...gen.Condition) IPolicySnapshotDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p policySnapshotDo) Or(conds ...gen.Condition) IPolicySnapshotDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p policySnapshotDo) Select(conds ...field.Expr) IPolicySnapshotDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p policySnapshotDo) Where(conds ...gen.Condition) IPolicySnapshotDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p policySnapshotDo) Order(conds ...field.Expr) IPolicySnapshotDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p policySnapshotDo) Distinct(cols ...field.Expr) IPolicySnapshotDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p policySnapshotDo) Omit(cols ...field.Expr) IPolicySnapshotDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p policySnapshotDo) Join(table schema.Tabler, on ...field.Expr) IPolicySnapshotDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p policySnapshotDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPolicySnapshotDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p policySnapshotDo) RightJoin(table schema.Tabler, on ...field.Expr) IPolicySnapshotDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p policySnapshotDo) Group(cols ...field.Expr) IPolicySnapshotDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p policySnapshotDo) Having(conds ...gen.Condition) IPolicySnapshotDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p policySnapshotDo) Limit(limit int) IPolicySnapshotDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p policySnapshotDo) Offset(offset int) IPolicySnapshotDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p policySnapshotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPolicySnapshotDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p policySnapshotDo) Unscoped() IPolicySnapshotDo {
	return p.withDO(p.DO.Unscoped())
}

func (p policySnapshotDo) Create(values ...*models.PolicySnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p policySnapshotDo) CreateInBatches(values []*models.PolicySnapshot, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p policySnapshotDo) Save(values ...*models.PolicySnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p policySnapshotDo) First() (*models.PolicySnapshot, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.PolicySnapshot), nil
	}
}

func (p policySnapshotDo) Take() (*models.PolicySnapshot, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.PolicySnapshot), nil
	}
}

func (p policySnapshotDo) Last() (*models.PolicySnapshot, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.PolicySnapshot), nil
	}
}

func (p policySnapshotDo) Find() ([]*models.PolicySnapshot, error) {
	result, err := p.DO.Find()
	return result.([]*models.PolicySnapshot), err
}

func (p policySnapshotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PolicySnapshot, err error) {
	buf := make([]*models.PolicySnapshot, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p policySnapshotDo) FindInBatches(result *[]*models.PolicySnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p policySnapshotDo) Attrs(attrs ...field.AssignExpr) IPolicySnapshotDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p policySnapshotDo) Assign(attrs ...field.AssignExpr) IPolicySnapshotDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p policySnapshotDo) Joins(fields ...field.RelationField) IPolicySnapshotDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p policySnapshotDo) Preload(fields ...field.RelationField) IPolicySnapshotDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p policySnapshotDo) FirstOrInit() (*models.PolicySnapshot, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.PolicySnapshot), nil
	}
}

func (p policySnapshotDo) FirstOrCreate() (*models.PolicySnapshot, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.PolicySnapshot), nil
	}
}

func (p policySnapshotDo) FindByPage(offset int, limit int) (result []*models.PolicySnapshot, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p policySnapshotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p policySnapshotDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p policySnapshotDo) Delete(models ...*models.PolicySnapshot) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *policySnapshotDo) withDO(do gen.Dao) *policySnapshotDo {
	p.DO = *do.(*gen.DO)
	return p
}
